'use strict';

import { TE, TD, B64, rand, concat, sha256, hmac, aesKey, aesEnc, aesDec, deriveKEK, hkdf, normalizePhone, newId, fingerprintJwk, genKeys, signBytes, verifyBytes, sharedSecret, signBundle, verifyBundle } from './crypto-core.js';

const now=()=>Date.now();
const BASE=new URL('.',location.href).pathname.replace(/\/$/,'');
const atBase=p=>BASE+(p.startsWith('/')?p:'/'+p);
const API_BASE='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms';
const PBKDF2_ITERS=600_000,AUTO_LOCK_MS=90_000,DB_NAME='MMS_APP_V4',DB_VER=1;
let db,installPrompt=null,pollTimer=null;
let session={id:null,master:null,vault:null,selected:null,lockTimer:null,lastActivity:0};

const $=id=>document.getElementById(id);
const gate=$('gate'),modal=$('modal'),contactsEl=$('contacts'),messagesEl=$('messages');
const mobileMQ=matchMedia('(max-width: 820px)');
function setMobileNav(active='chats'){for(const id of ['mobileChatsBtn','mobileGuestBtn','mobileSecurityBtn'])$(id)?.classList.remove('active');const map={chats:'mobileChatsBtn',guest:'mobileGuestBtn',security:'mobileSecurityBtn'};$(map[active]||'mobileChatsBtn')?.classList.add('active')}
function showMobileChats(){document.body.classList.remove('mobile-chat');setMobileNav('chats')}
function showMobileChat(){if(mobileMQ.matches)document.body.classList.add('mobile-chat')}

function isStandalone(){return matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function isMobileDevice(){return mobileMQ.matches||/android|iphone|ipad|ipod/i.test(navigator.userAgent)}
function syncInstallUI(){
  const installed=isStandalone();
  $('installBtn')?.classList.toggle('hidden',installed||!installPrompt);
  $('mobileInstallBtn')?.classList.toggle('hidden',installed||!isMobileDevice());
}
async function requestInstall(){
  if(isStandalone()){showInstallHelp(true);return}
  if(isIOS()){showInstallHelp(false);return}
  if(installPrompt){
    const p=installPrompt; installPrompt=null;
    try{await p.prompt();await p.userChoice}catch{}
    syncInstallUI(); return;
  }
  showInstallHelp(false);
}
function showInstallHelp(installed=false){
  modal.innerHTML='<h2>'+(installed?'MMS staat al als app':'Installeer MMS op je telefoon')+'</h2>';
  const intro=document.createElement('div');intro.className='notice good';intro.textContent='Geen App Store of Play Store nodig. MMS wordt vanaf deze beveiligde HTTPS-webapp op je beginscherm geïnstalleerd.';
  const steps=document.createElement('div');steps.className='installSteps';
  if(isIOS()) steps.innerHTML='<strong>iPhone / iPad</strong><ol><li>Open MMS in <b>Safari</b>.</li><li>Tik onderin op <b>Delen</b> (vierkant met pijl omhoog).</li><li>Kies <b>Zet op beginscherm</b>.</li><li>Tik op <b>Voeg toe</b>.</li></ol><p>MMS opent daarna als zelfstandige app vanaf je beginscherm.</p>';
  else steps.innerHTML='<strong>Android</strong><ol><li>Open MMS in Chrome of een ondersteunde browser.</li><li>Open het browsermenu.</li><li>Kies <b>App installeren</b> of <b>Toevoegen aan startscherm</b>.</li><li>Bevestig <b>Installeren</b>.</li></ol><p>Als de browser een native installatiepopup aanbiedt, gebruikt MMS die automatisch.</p>';
  const security=document.createElement('div');security.className='notice';security.textContent='Installeren verandert de E2EE niet. Je lokale versleutelde vault blijft op dit apparaat en de relay krijgt daardoor geen extra decryptiesleutel.';
  const close=document.createElement('button');close.className='btn primary';close.style.width='100%';close.textContent='Begrepen';close.onclick=()=>modal.classList.add('hidden');
  modal.append(intro,steps,security,close);modal.classList.remove('hidden');
}
function addInstallGateButton(card){
  if(!isMobileDevice()||isStandalone())return;
  const box=document.createElement('div');box.className='installGate';
  const copy=document.createElement('div');copy.innerHTML='<strong>Maak hiervan een telefoonapp</strong><small>Zonder App Store-kosten · direct op je beginscherm</small>';
  const b=document.createElement('button');b.className='btn primary';b.textContent='Installeer MMS';b.onclick=requestInstall;
  box.append(copy,b);card.append(box);
}


function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{const d=r.result;['accounts','vaults'].forEach(s=>{if(!d.objectStoreNames.contains(s))d.createObjectStore(s,{keyPath:'id'})})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function idbGet(store,id){return new Promise((res,rej)=>{const r=tx(store).get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
function idbPut(store,val){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(val);r.onsuccess=()=>res(val);r.onerror=()=>rej(r.error)})}
function idbAll(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}


async function api(path,opt={}){const method=(opt.method||'GET').toUpperCase(),retryable=method==='GET'||path==='/api/discover',attempts=retryable?2:1;let last;for(let attempt=0;attempt<attempts;attempt++){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),12000);try{const r=await fetch(API_BASE+path,{...opt,signal:ac.signal,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}catch(e){last=e;if(attempt+1<attempts)await new Promise(r=>setTimeout(r,350))}finally{clearTimeout(timer)}}throw new Error(last?.name==='AbortError'?'relay_timeout':(last?.message||'relay_unreachable'))}
async function relayHealth(){try{const h=await api('/api/health');$('relayState').classList.toggle('ok',!!h.ok);$('relayState').querySelector('span').textContent=h.ok?'relay online':'relay fout';return true}catch{$('relayState').classList.remove('ok');$('relayState').querySelector('span').textContent='relay offline';return false}}
function authHeader(){return session.vault?{'Authorization':'Bearer '+session.vault.mailboxAuth}:{}}

async function encryptVault(){if(!session.master||!session.vault)return;const rec=await idbGet('vaults',session.id);if(!rec?.wrap)throw new Error('Vault wrapper ontbreekt.');rec.box=await aesEnc(session.master,JSON.stringify(session.vault),'MMS-V4-VAULT:'+session.id);rec.updatedAt=now();await idbPut('vaults',rec)}
async function decryptVault(id,master){const rec=await idbGet('vaults',id);if(!rec)throw new Error('Vault ontbreekt.');return JSON.parse(TD.decode(await aesDec(master,rec.box,'MMS-V4-VAULT:'+id)))}

async function createAccount(label,password){
  label=label.trim();if(label.length<2)throw new Error('Naam is te kort.');if(password.length<16)throw new Error('Gebruik minimaal 16 tekens voor het MMS-wachtwoord.');
  const id=newId(),keys=await genKeys(),mailboxAuth=B64.url(rand(32)),authHash=B64.url(await sha256(mailboxAuth)),bundleSig=await signBundle(keys,id);
  await api('/api/register',{method:'POST',body:JSON.stringify({id,authHash,signAlg:keys.signAlg,agreeAlg:keys.agreeAlg,signPub:keys.signPub,agreePub:keys.agreePub,bundleSig})});
  const master=rand(32),salt=rand(32),kek=await deriveKEK(password,salt),wrapped=await aesEnc(kek,master,'MMS-V4-MASTER:'+id);
  const vault={v:4,phone:null,mailboxAuth,privateKeys:{signPriv:keys.signPriv,agreePriv:keys.agreePriv},public:{id,signAlg:keys.signAlg,agreeAlg:keys.agreeAlg,signPub:keys.signPub,agreePub:keys.agreePub,bundleSig},contacts:{},chats:{},ratchets:{},seen:{},security:{createdAt:now(),lastPasswordChange:now()}};
  const box=await aesEnc(master,JSON.stringify(vault),'MMS-V4-VAULT:'+id);
  await idbPut('accounts',{id,label,createdAt:now(),signFingerprint:await fingerprintJwk(keys.signPub)});
  await idbPut('vaults',{id,wrap:{salt:B64.enc(salt),iters:PBKDF2_ITERS,wrapped},box,updatedAt:now()});
  return id;
}
async function syncProfileRegistration(){if(!session.vault)return;const v=session.vault,authHash=B64.url(await sha256(v.mailboxAuth));const body={id:session.id,authHash,signAlg:v.public.signAlg,agreeAlg:v.public.agreeAlg,signPub:v.public.signPub,agreePub:v.public.agreePub,bundleSig:v.public.bundleSig};if(v.phone)body.phone=v.phone;return api('/api/register',{method:'POST',body:JSON.stringify(body)})}
async function unlock(id,password){const rec=await idbGet('vaults',id);if(!rec?.wrap)throw new Error('Accountdata ontbreekt.');const kek=await deriveKEK(password,B64.dec(rec.wrap.salt),rec.wrap.iters);let master;try{master=await aesDec(kek,rec.wrap.wrapped,'MMS-V4-MASTER:'+id)}catch{throw new Error('Onjuist wachtwoord of beschadigde vault.')}const vault=await decryptVault(id,master);session={id,master,vault,selected:null,lockTimer:null,lastActivity:now()};touch();gate.classList.add('hidden');enableUnlocked(true);try{await syncProfileRegistration()}catch(e){console.warn('MMS profiel-sync uitgesteld:',e.message)}await renderApp();startPolling()}
function wipeSession(){if(session.lockTimer)clearTimeout(session.lockTimer);stopPolling();session={id:null,master:null,vault:null,selected:null,lockTimer:null,lastActivity:0}}
function lock(){wipeSession();enableUnlocked(false);$('messageInput').value='';showMobileChats();renderLocked();renderGate();modal.classList.add('hidden')}
function touch(){if(!session.master)return;session.lastActivity=now();if(session.lockTimer)clearTimeout(session.lockTimer);session.lockTimer=setTimeout(lock,AUTO_LOCK_MS)}
function enableUnlocked(on){for(const id of ['inviteBtn','guestBtn','securityBtn','lockBtn','inviteInput','addInviteBtn','inviteCodeBtn','mobileLockBtn','mobileInviteBtn','mobileGuestBtn','mobileSecurityBtn']){const el=$(id);if(el)el.disabled=!on}}

async function contactRoot(p){if(p.agreeAlg!==session.vault.public.agreeAlg)throw new Error('Deze twee clients gebruiken verschillende key-agreement algoritmes.');const ss=await sharedSecret(session.vault.privateKeys.agreePriv,session.vault.public.agreeAlg,p.agreePub);const ids=[session.id,p.id].sort().join('|');return hkdf(ss,await sha256('MMS-V4|'+ids),'MMS-V4-ROOT|'+ids)}
async function initialRatchets(peerId,root){const salt=await sha256('MMS-V4-DIRECTION');return{send:B64.enc(await hkdf(root,salt,'MMS-V4-CHAIN|'+session.id+'>'+peerId)),sendN:0,recv:B64.enc(await hkdf(root,salt,'MMS-V4-CHAIN|'+peerId+'>'+session.id)),recvN:0}}
async function nextChain(chain){return hmac(chain,'MMS-V4-NEXT')}
async function msgKey(chain,n){return hmac(chain,'MMS-V4-MESSAGE|'+n)}
function canonicalHead(e){return JSON.stringify({v:4,id:e.id,from:e.from,to:e.to,n:e.n,ts:e.ts,iv:e.iv})}

function canonicalGuestHead(inviteId,e){return JSON.stringify({v:5,inviteId,id:e.id,dir:e.dir,n:e.n,ts:e.ts,iv:e.iv})}
async function guestSecret(inviteId,linkPart,codePart){return hkdf(concat(linkPart,codePart),await sha256('MMS-GUEST-SECRET|'+inviteId),'MMS-GUEST-SECRET-V1|'+inviteId)}
async function guestAuthToken(inviteId,secret){return B64.url(await hkdf(secret,await sha256('MMS-GUEST-AUTH|'+inviteId),'MMS-GUEST-AUTH-V1|'+inviteId))}
async function guestInitialRatchets(inviteId,secret){const salt=await sha256('MMS-GUEST-DIRECTION|'+inviteId);return{send:B64.enc(await hkdf(secret,salt,'MMS-GUEST-CHAIN|owner>guest')),sendN:0,recv:B64.enc(await hkdf(secret,salt,'MMS-GUEST-CHAIN|guest>owner')),recvN:0}}
async function guestNextChain(chain){return hmac(chain,'MMS-V5-GUEST-NEXT')}
async function guestMsgKey(chain,n){return hmac(chain,'MMS-V5-GUEST-MESSAGE|'+n)}
async function guestSafety(secret){const d=await sha256(concat(TE.encode('MMS-GUEST-SAFETY|'),secret));return[...d.slice(0,12)].map(x=>x.toString().padStart(3,'0')).join(' ').match(/.{1,15}/g).join(' · ')}
function guestContactKey(inviteId){return 'guest:'+inviteId}
function formatGuestCode(raw){return raw.match(/.{1,4}/g)?.join('-')||raw}
function guestLink(inviteId,linkPart){return location.origin+atBase('/guest.html')+'?i='+encodeURIComponent(inviteId)+'#a='+B64.url(linkPart)}
async function createGuestInvite(name,firstMessage,minutes=30){
  name=(name||'Secure Guest').trim().slice(0,80)||'Secure Guest';
  const inviteId=newId(18),linkPart=rand(16),codePart=rand(16),secret=await guestSecret(inviteId,linkPart,codePart),authToken=await guestAuthToken(inviteId,secret),expiresAt=now()+Math.max(5,Math.min(1440,minutes))*60_000;
  await api('/api/guest/create',{method:'POST',headers:authHeader(),body:JSON.stringify({ownerId:session.id,inviteId,authHash:B64.url(await sha256(authToken)),expiresAt})});
  const key=guestContactKey(inviteId),rat=await guestInitialRatchets(inviteId,secret),safety=await guestSafety(secret);
  session.vault.contacts[key]={id:key,type:'guest',inviteId,name,phone:null,addedAt:now(),expiresAt,claimed:false,guestSafety:safety,guestShare:{linkPart:B64.url(linkPart),codePart:B64.url(codePart)}};
  session.vault.ratchets[key]=rat;session.vault.chats[key]=[];session.selected=key;await encryptVault();
  if((firstMessage||'').trim())await sendGuestMessage(key,firstMessage.trim());
  return{key,inviteId,link:guestLink(inviteId,linkPart),code:formatGuestCode(B64.url(codePart)),expiresAt,safety};
}
async function sendGuestMessage(contactKey,text){
  text=text.trim();const c=session.vault.contacts[contactKey],rat=session.vault.ratchets[contactKey];if(!c||c.type!=='guest'||!rat)throw new Error('Guest-beveiliging ontbreekt.');if(c.expiresAt<=now())throw new Error('Deze Secure Guest-uitnodiging is verlopen.');
  const n=rat.sendN,chain=B64.dec(rat.send),key=await guestMsgKey(chain,n),iv=rand(12),id=newId(18),ts=now(),account=await idbGet('accounts',session.id),payload={t:'msg',text,label:account?.label||'MMS'};
  const head={v:5,id,dir:'owner>guest',n,ts,iv:B64.enc(iv)},aad=canonicalGuestHead(c.inviteId,head),k=await aesKey(key),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:TE.encode(aad),tagLength:128},k,TE.encode(JSON.stringify(payload)))),sig=await signBytes(session.vault.privateKeys.signPriv,session.vault.public.signAlg,concat(TE.encode(aad),ct)),env={...head,ct:B64.enc(ct),sig:B64.enc(sig)};
  rat.send=B64.enc(await guestNextChain(chain));rat.sendN=n+1;session.vault.chats[contactKey].push({id,dir:'out',text,ts,n});await encryptVault();
  await api('/api/guest/owner-send/'+encodeURIComponent(c.inviteId),{method:'POST',headers:authHeader(),body:JSON.stringify({envelope:env})});await renderMessages();
}
async function receiveGuestEnvelope(contactKey,env){
  const c=session.vault.contacts[contactKey];if(!c||c.type!=='guest'||env?.v!==5||env.dir!=='guest>owner'||!env.id)throw new Error('bad_guest_envelope');if(session.vault.seen[env.id])return;
  const rat=session.vault.ratchets[contactKey];if(env.n<rat.recvN){session.vault.seen[env.id]=1;return}if(env.n-rat.recvN>100)throw new Error('guest_ratchet_gap');let chain=B64.dec(rat.recv),n=rat.recvN;while(n<env.n){chain=await guestNextChain(chain);n++}
  const key=await guestMsgKey(chain,env.n),aad=canonicalGuestHead(c.inviteId,env),k=await aesKey(key);let pt;try{pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:B64.dec(env.iv),additionalData:TE.encode(aad),tagLength:128},k,B64.dec(env.ct))}catch{throw new Error('guest_decrypt_failed')}
  let payload;try{payload=JSON.parse(TD.decode(pt))}catch{throw new Error('bad_guest_payload')}if(payload.t!=='msg'||typeof payload.text!=='string'||payload.text.length>10000)throw new Error('unsupported_guest_payload');
  rat.recv=B64.enc(await guestNextChain(chain));rat.recvN=env.n+1;session.vault.seen[env.id]=1;session.vault.chats[contactKey].push({id:env.id,dir:'in',text:payload.text,ts:env.ts,n:env.n});
}
async function pollGuestInboxes(){
  if(!session.master)return;let changed=false;for(const c of Object.values(session.vault.contacts)){if(c.type!=='guest'||c.expiresAt<=now())continue;try{const r=await api('/api/guest/owner/'+encodeURIComponent(c.inviteId),{headers:authHeader()});if(r.claimed&&!c.claimed){c.claimed=true;c.claimedAt=r.claimedAt||now();delete c.guestShare;changed=true}for(const env of r.items||[]){try{await receiveGuestEnvelope(c.id,env);changed=true}catch(e){console.warn('MMS rejected guest envelope:',e.message)}}}catch(e){if(!['unauthorized','guest_invite_expired'].includes(e.message))console.warn('Guest poll:',e.message)}}if(changed){await encryptVault();await renderApp()}}

function encodeInvite(){const a=session.vault.public;const localLabel=session.id;return 'MMS4.'+B64.url(TE.encode(JSON.stringify({v:4,id:a.id,label:localLabel,signAlg:a.signAlg,agreeAlg:a.agreeAlg,signPub:a.signPub,agreePub:a.agreePub,bundleSig:a.bundleSig})))}
function decodeInvite(code){code=code.trim();if(!code.startsWith('MMS4.'))throw new Error('Ongeldige MMS invite-code.');let o;try{o=JSON.parse(TD.decode(B64.unurl(code.slice(5))))}catch{throw new Error('Invite-code kan niet worden gelezen.')}if(o.v!==4||!o.id||!o.signPub||!o.agreePub||!o.bundleSig)throw new Error('Invite-code mist beveiligingsdata.');return o}
async function addInvite(code){const inv=decodeInvite(code);if(inv.id===session.id)throw new Error('Dit is je eigen MMS-identiteit.');const {profile:p}=await api('/api/profile/'+encodeURIComponent(inv.id));const local={id:inv.id,signAlg:inv.signAlg,agreeAlg:inv.agreeAlg,signPub:inv.signPub,agreePub:inv.agreePub,bundleSig:inv.bundleSig};if(JSON.stringify(p)!==JSON.stringify({...p})||!(await verifyBundle(p)))throw new Error('Serverprofiel heeft een ongeldige identity signature.');const serverFp=await fingerprintJwk(p.signPub),inviteFp=await fingerprintJwk(local.signPub);if(serverFp!==inviteFp||p.bundleSig!==local.bundleSig)throw new Error('Invite komt niet overeen met de server identity — geblokkeerd.');const account=await idbGet('accounts',session.id);const alias='MMS '+inv.id.slice(0,7);const root=await contactRoot(p);session.vault.contacts[p.id]={id:p.id,name:alias,phone:null,pinnedSignFingerprint:serverFp,signPub:p.signPub,agreePub:p.agreePub,signAlg:p.signAlg,agreeAlg:p.agreeAlg,addedAt:now(),verified:false,numberSharedOut:false};session.vault.ratchets[p.id]=await initialRatchets(p.id,root);session.vault.chats[p.id]=session.vault.chats[p.id]||[];await encryptVault();session.selected=p.id;await renderApp();await pollInbox()}
async function addPhoneContact(phone){phone=normalizePhone(phone);const {profile:p}=await api('/api/discover',{method:'POST',headers:authHeader(),body:JSON.stringify({requesterId:session.id,phone})});if(!p||p.id===session.id)throw new Error(p?.id===session.id?'Dit is je eigen telefoonnummer.':'Geen MMS-profiel gevonden.');if(!(await verifyBundle(p)))throw new Error('Serverprofiel heeft een ongeldige identity signature.');const fp=await fingerprintJwk(p.signPub);const existing=session.vault.contacts[p.id];if(existing){existing.phone=phone;existing.name=existing.name||phone;session.selected=p.id;await encryptVault();await renderApp();return}const root=await contactRoot(p);session.vault.contacts[p.id]={id:p.id,name:phone,phone,pinnedSignFingerprint:fp,signPub:p.signPub,agreePub:p.agreePub,signAlg:p.signAlg,agreeAlg:p.agreeAlg,addedAt:now(),verified:false,phoneDiscovery:true,numberSharedOut:false};session.vault.ratchets[p.id]=await initialRatchets(p.id,root);session.vault.chats[p.id]=session.vault.chats[p.id]||[];session.selected=p.id;await encryptVault();await renderApp();await pollInbox()}

async function sendMessage(text){text=text.trim();if(!text||!session.selected)return;touch();const peerId=session.selected,c=session.vault.contacts[peerId];if(c?.type==='guest')return sendGuestMessage(peerId,text);const rat=session.vault.ratchets[peerId];if(!c||!rat)throw new Error('Contactbeveiliging ontbreekt.');const n=rat.sendN,chain=B64.dec(rat.send),key=await msgKey(chain,n),iv=rand(12),id=newId(18),ts=now();const payload={t:'msg',text};if(!c.numberSharedOut){payload.phone=session.vault.phone;c.numberSharedOut=true}const head={v:4,id,from:session.id,to:peerId,n,ts,iv:B64.enc(iv)},aad=canonicalHead(head),k=await aesKey(key);const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:TE.encode(aad),tagLength:128},k,TE.encode(JSON.stringify(payload))));const sig=await signBytes(session.vault.privateKeys.signPriv,session.vault.public.signAlg,concat(TE.encode(aad),ct));const env={...head,ct:B64.enc(ct),sig:B64.enc(sig)};rat.send=B64.enc(await nextChain(chain));rat.sendN=n+1;session.vault.chats[peerId].push({id,dir:'out',text,ts,n});await encryptVault();try{await api('/api/send',{method:'POST',headers:authHeader(),body:JSON.stringify({from:session.id,to:peerId,envelope:env})})}catch(e){session.vault.chats[peerId].push({id:newId(12),dir:'sys',text:'Verzenden mislukt: '+e.message,ts:now(),n:-1});await encryptVault();throw e}await renderMessages()}

async function receiveEnvelope(env){if(env.v!==4||env.to!==session.id||!env.id)throw new Error('routing_mismatch');if(session.vault.seen[env.id])return;const c=session.vault.contacts[env.from];if(!c)throw new Error('unknown_sender');const {profile:p}=await api('/api/profile/'+encodeURIComponent(env.from));if(!(await verifyBundle(p)))throw new Error('bad_identity_bundle');const fp=await fingerprintJwk(p.signPub);if(fp!==c.pinnedSignFingerprint)throw new Error('IDENTITY_KEY_CHANGED');const aad=canonicalHead(env),ct=B64.dec(env.ct),ok=await verifyBytes(c.signPub,c.signAlg,B64.dec(env.sig),concat(TE.encode(aad),ct));if(!ok)throw new Error('bad_signature');const rat=session.vault.ratchets[env.from];if(env.n<rat.recvN){session.vault.seen[env.id]=1;return}if(env.n-rat.recvN>100)throw new Error('ratchet_gap');let chain=B64.dec(rat.recv),n=rat.recvN;while(n<env.n){chain=await nextChain(chain);n++}const key=await msgKey(chain,env.n),k=await aesKey(key);let pt;try{pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:B64.dec(env.iv),additionalData:TE.encode(aad),tagLength:128},k,ct)}catch{throw new Error('decrypt_failed')}let payload;try{payload=JSON.parse(TD.decode(pt))}catch{throw new Error('bad_payload')}if(payload.t!=='msg'||typeof payload.text!=='string'||payload.text.length>10000)throw new Error('unsupported_payload');if(payload.phone){try{c.phone=normalizePhone(payload.phone)}catch{}}rat.recv=B64.enc(await nextChain(chain));rat.recvN=env.n+1;session.vault.seen[env.id]=1;session.vault.chats[env.from]=session.vault.chats[env.from]||[];session.vault.chats[env.from].push({id:env.id,dir:'in',text:payload.text,ts:env.ts,n:env.n})}
async function pollInbox(){if(!session.master)return;try{const {items}=await api('/api/inbox/'+encodeURIComponent(session.id),{headers:authHeader()});const failed=[];for(const env of items||[]){try{await receiveEnvelope(env)}catch(e){if(e.message==='unknown_sender')failed.push(env);else console.warn('MMS rejected encrypted envelope:',e.message)}}if(failed.length)await api('/api/inbox/restore/'+encodeURIComponent(session.id),{method:'POST',headers:authHeader(),body:JSON.stringify({items:failed})});if((items||[]).length){await encryptVault();await renderApp()}await pollGuestInboxes();await relayHealth()}catch{await relayHealth()}}
function startPolling(){stopPolling();pollTimer=setInterval(()=>pollInbox(),1800);pollInbox()}
function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}

async function safetyCode(peerId){const c=session.vault.contacts[peerId];if(c?.type==='guest')return c.guestSafety||'guest';const mine=await fingerprintJwk(session.vault.public.signPub),theirs=c.pinnedSignFingerprint,d=await sha256([mine,theirs].sort().join('|'));return[...d.slice(0,15)].map(x=>x.toString().padStart(3,'0')).join(' ').match(/.{1,15}/g).join('\n')}
async function changePassword(oldPw,newPw){if(newPw.length<16)throw new Error('Nieuw wachtwoord moet minimaal 16 tekens zijn.');const rec=await idbGet('vaults',session.id),old=await deriveKEK(oldPw,B64.dec(rec.wrap.salt),rec.wrap.iters);let m;try{m=await aesDec(old,rec.wrap.wrapped,'MMS-V4-MASTER:'+session.id)}catch{throw new Error('Huidig wachtwoord klopt niet.')}const salt=rand(32),kek=await deriveKEK(newPw,salt);rec.wrap={salt:B64.enc(salt),iters:PBKDF2_ITERS,wrapped:await aesEnc(kek,m,'MMS-V4-MASTER:'+session.id)};await idbPut('vaults',rec);session.vault.security.lastPasswordChange=now();await encryptVault()}

function field(label,type='text',placeholder=''){const w=document.createElement('div');w.className='field';const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type=type;i.placeholder=placeholder;i.autocomplete=type==='password'?'new-password':'off';w.append(l,i);return{w,i}}
async function renderGate(){const accounts=await idbAll('accounts');gate.classList.remove('hidden');gate.innerHTML='';const c=document.createElement('div');c.className='card';c.innerHTML='<h1>MMS Secure Vault</h1><p>Privésleutels en chats blijven lokaal versleuteld. Je telefoonnummer wordt alleen voor MMS-discovery verwerkt; de database bewaart geen leesbaar nummer.</p>';addInstallGateButton(c);if(accounts.length){const list=document.createElement('div');list.className='accounts';for(const a of accounts){const r=document.createElement('div');r.className='account';const d=document.createElement('div');const s=document.createElement('strong');s.textContent=a.label;const sm=document.createElement('small');sm.textContent='MMS ID '+a.id.slice(0,10)+'…';d.append(s,sm);const b=document.createElement('button');b.className='btn primary';b.textContent='Ontgrendel';b.onclick=()=>showUnlock(a);r.append(d,b);list.append(r)}c.append(list)}const n=document.createElement('button');n.className='btn';n.style.width='100%';n.textContent='＋ Nieuwe MMS-identiteit';n.onclick=showCreate;c.append(n);gate.append(c)}
function showCreate(){gate.innerHTML='';const c=document.createElement('div');c.className='card';c.innerHTML='<h2>Nieuwe MMS-identiteit</h2><div class="notice">E2EE staat altijd aan. Voor een MMS-account is <strong>geen telefoonnummer nodig</strong>. Je kunt later contacten toevoegen met een invite-code; telefoon-discovery kan later optioneel worden gekoppeld.</div>';const n=field('Naam op dit apparaat','text','Querijn'),pw=field('MMS-wachtwoord','password','minimaal 16 tekens'),pw2=field('Herhaal wachtwoord','password','');const e=document.createElement('div');e.className='error';const row=document.createElement('div');row.className='row';const back=document.createElement('button');back.className='btn';back.textContent='Terug';back.onclick=renderGate;const go=document.createElement('button');go.className='btn primary';go.textContent='Maak identiteit';go.onclick=async()=>{e.textContent='';if(pw.i.value!==pw2.i.value){e.textContent='Wachtwoorden zijn niet gelijk.';return}go.disabled=true;back.disabled=true;const old=go.textContent;go.textContent='Bezig met beveiligen…';e.style.color='var(--muted)';e.textContent='Sleutels en lokale vault worden aangemaakt…';await new Promise(r=>requestAnimationFrame(()=>setTimeout(r,0)));try{const id=await createAccount(n.i.value,pw.i.value);e.textContent='';await unlock(id,pw.i.value)}catch(err){e.style.color='';const m=err?.message||'Aanmaken mislukt.';e.textContent=(m==='Failed to fetch'||m==='relay_unreachable')?'Kan MMS-relay niet bereiken. Controleer internet en probeer opnieuw.':m;go.textContent=old;go.disabled=false;back.disabled=false}};pw2.i.onkeydown=ev=>{if(ev.key==='Enter')go.click()};row.append(back,go);c.append(n.w,pw.w,pw2.w,e,row);gate.append(c);setTimeout(()=>n.i.focus(),0)}
function showUnlock(a){gate.innerHTML='';const c=document.createElement('div');c.className='card';c.innerHTML='<h2></h2><p>Voer je lokale MMS-wachtwoord in. Het wachtwoord wordt niet naar de relay gestuurd.</p>';c.querySelector('h2').textContent=a.label;const pw=field('Wachtwoord','password',''),e=document.createElement('div');e.className='error';pw.i.autocomplete='current-password';const row=document.createElement('div');row.className='row';const back=document.createElement('button');back.className='btn';back.textContent='Terug';back.onclick=renderGate;const go=document.createElement('button');go.className='btn primary';go.textContent='Ontgrendel';go.onclick=async()=>{e.textContent='';go.disabled=true;try{await unlock(a.id,pw.i.value)}catch(err){e.textContent=err.message}finally{go.disabled=false}};pw.i.onkeydown=ev=>{if(ev.key==='Enter')go.click()};row.append(back,go);c.append(pw.w,e,row);gate.append(c);setTimeout(()=>pw.i.focus(),0)}

function renderLocked(){$('meName').textContent='Vergrendeld';$('meInfo').textContent='Geen actieve identiteit';$('chatTitle').textContent='MMS Secure Messaging';$('chatSecure').textContent='🔒 E2EE is verplicht';contactsEl.innerHTML='';messagesEl.innerHTML='<div class="empty"><h2>🔒 MMS is vergrendeld</h2><p>De master key en privésleutels zijn uit de actieve sessie verwijderd.</p></div>';$('messageInput').disabled=true;$('sendBtn').disabled=true}
async function renderApp(){if(!session.master)return renderLocked();touch();const a=await idbGet('accounts',session.id);$('meName').textContent=a.label;const idLine=session.vault.phone?session.vault.phone:('MMS '+session.id.slice(0,8)+'…');$('meInfo').textContent='🔐 '+idLine+' · '+session.vault.public.agreeAlg+' · '+session.vault.public.signAlg;await renderContacts();await renderMessages()}
async function renderContacts(){contactsEl.innerHTML='';for(const c of Object.values(session.vault.contacts)){const b=document.createElement('button');b.className='contact'+(session.selected===c.id?' active':'');const av=document.createElement('div');av.className='avatar';av.textContent=(c.name||'M').slice(0,1).toUpperCase();const mid=document.createElement('div');const n=document.createElement('div');n.className='name';n.textContent=c.name||(c.type==='guest'?'Secure Guest':('MMS '+c.id.slice(0,7)));const p=document.createElement('div');p.className='preview';const msgs=(session.vault.chats[c.id]||[]).filter(x=>x.dir!=='sys');if(msgs.length)p.textContent=msgs[msgs.length-1].text;else if(c.type==='guest')p.textContent=c.expiresAt<=now()?'Guest verlopen':(c.claimed?'Guest verbonden':'Wacht op guest');else p.textContent=c.phone?'Nummer ontvangen':'Beveiligd contact';mid.append(n,p);const badge=document.createElement('span');badge.className='badge';badge.textContent=c.type==='guest'?'GUEST':'E2EE';b.append(av,mid,badge);b.onclick=async()=>{session.selected=c.id;await renderContacts();await renderMessages();showMobileChat()};contactsEl.append(b)}}
async function renderMessages(){messagesEl.innerHTML='';const i=$('messageInput'),s=$('sendBtn');if(!session.master||!session.selected){i.disabled=true;s.disabled=true;$('chatTitle').textContent='MMS Secure Messaging';$('chatSecure').textContent='🔒 E2EE is verplicht';messagesEl.innerHTML='<div class="empty"><h2>Voeg een beveiligd contact toe</h2><p>Gebruik een MMS invite-code of maak een Secure Guest voor iemand zonder MMS.</p></div>';return}const c=session.vault.contacts[session.selected];$('chatTitle').textContent=c.name||(c.type==='guest'?'Secure Guest':('MMS '+c.id.slice(0,7)));if(c.type==='guest'){$('chatSecure').textContent='🔒 Secure Guest E2EE · '+(c.claimed?'verbonden':'wacht op opening')+' · safety '+(c.guestSafety||'').slice(0,45);i.disabled=c.expiresAt<=now();s.disabled=i.disabled}else{$('chatSecure').textContent='🔒 E2EE · safety '+(await safetyCode(c.id)).replace(/\n/g,' · ').slice(0,55)+'…';i.disabled=false;s.disabled=false}const msgs=session.vault.chats[c.id]||[];if(!msgs.length)messagesEl.innerHTML='<div class="empty"><h2>Beveiligd gesprek</h2><p>'+(c.type==='guest'?'De guest hoeft MMS niet geïnstalleerd te hebben. Alleen ciphertext staat op de relay.':'De relay ontvangt alleen gesigneerde ciphertext-envelopes.')+'</p></div>';for(const m of msgs){if(m.dir==='sys')continue;const b=document.createElement('div');b.className='bubble '+m.dir;b.append(document.createTextNode(m.text));const meta=document.createElement('div');meta.className='meta';meta.textContent=(m.dir==='out'?'Jij':'Ontvangen')+' · '+new Date(m.ts).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · #'+m.n;b.append(meta);messagesEl.append(b)}messagesEl.scrollTop=messagesEl.scrollHeight}

function showInviteCodeAdder(){modal.innerHTML='<h2>Invite-code gebruiken</h2><p>Alleen nodig als zoeken op telefoonnummer niet beschikbaar is.</p>';const box=document.createElement('textarea');box.rows=5;box.placeholder='MMS4.…';const e=document.createElement('div');e.className='error';const go=document.createElement('button');go.className='btn primary';go.style.cssText='width:100%;margin-top:8px';go.textContent='Contact toevoegen';go.onclick=async()=>{e.textContent='';go.disabled=true;try{const raw=decodeInvite(box.value);await addInvite(box.value);const c=session.vault.contacts[raw.id];if(raw.label)c.name=raw.label;await encryptVault();modal.classList.add('hidden')}catch(err){e.textContent=err.message}finally{go.disabled=false}};const close=document.createElement('button');close.className='btn';close.style.cssText='width:100%;margin-top:8px';close.textContent='Sluiten';close.onclick=()=>modal.classList.add('hidden');modal.append(box,e,go,close);modal.classList.remove('hidden')}
function showMobileContactActions(){modal.innerHTML='<h2>Contact</h2><p>Zoek primair op telefoonnummer of gebruik een invite-code als fallback.</p>';const phone=document.createElement('button');phone.className='btn primary';phone.style.cssText='width:100%;margin-top:8px';phone.textContent='Zoek op telefoonnummer';phone.onclick=()=>{modal.classList.add('hidden');showMobileChats();setTimeout(()=>{$('inviteInput').focus();$('inviteInput').scrollIntoView({behavior:'smooth',block:'center'})},80)};const paste=document.createElement('button');paste.className='btn';paste.style.cssText='width:100%;margin-top:8px';paste.textContent='Invite-code gebruiken';paste.onclick=showInviteCodeAdder;const mine=document.createElement('button');mine.className='btn';mine.style.cssText='width:100%;margin-top:8px';mine.textContent='Deel mijn MMS invite';mine.onclick=showInvite;const close=document.createElement('button');close.className='btn';close.style.cssText='width:100%;margin-top:8px';close.textContent='Sluiten';close.onclick=()=>modal.classList.add('hidden');modal.append(phone,paste,mine,close);modal.classList.remove('hidden')}

async function showGuestCreator(){modal.innerHTML='<h2>MMS Secure Guest</h2><p>Voor iemand zonder MMS. De link en toegangscode moeten via <strong>verschillende kanalen</strong> worden gedeeld; samen vormen ze de E2EE-capability.</p><div class="notice">Gewone SMS-fallback blijft uit. De relay krijgt nooit het bericht, de toegangscode of de uiteindelijke guest-sleutel in plaintext.</div>';const nm=field('Naam van de guest (alleen lokaal)','text','Bijv. Sarah');const msg=field('Eerste bericht (optioneel)','text','Dit staat al versleuteld klaar');const e=document.createElement('div');e.className='error';const row=document.createElement('div');row.className='row';const close=document.createElement('button');close.className='btn';close.textContent='Annuleren';close.onclick=()=>modal.classList.add('hidden');const go=document.createElement('button');go.className='btn primary';go.textContent='Maak Secure Guest';go.onclick=async()=>{e.textContent='';go.disabled=true;try{const g=await createGuestInvite(nm.i.value,msg.i.value,30);showGuestShare(g)}catch(err){e.textContent=err.message;go.disabled=false}};row.append(close,go);modal.append(nm.w,msg.w,e,row);modal.classList.remove('hidden')}
function showGuestShare(g){modal.innerHTML='<h2>Secure Guest klaar</h2><p>De uitnodiging is eenmalig te claimen en verloopt om '+new Date(g.expiresAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+'.</p>';const w=document.createElement('div');w.className='notice good';w.textContent='Stuur de LINK via kanaal 1 en de TOEGANGSCODE via een ander kanaal. Zet ze niet in hetzelfde SMS-, mail- of chatbericht.';const l1=document.createElement('label');l1.textContent='1 · Guest-link';const box1=document.createElement('div');box1.className='codebox';box1.textContent=g.link;const cp1=document.createElement('button');cp1.className='btn primary';cp1.style.cssText='width:100%;margin-top:8px';cp1.textContent='Kopieer link';cp1.onclick=()=>navigator.clipboard?.writeText(g.link);const l2=document.createElement('label');l2.style.cssText='display:block;margin-top:14px';l2.textContent='2 · Aparte toegangscode';const box2=document.createElement('div');box2.className='codebox';box2.textContent=g.code;const cp2=document.createElement('button');cp2.className='btn primary';cp2.style.cssText='width:100%;margin-top:8px';cp2.textContent='Kopieer toegangscode';cp2.onclick=()=>navigator.clipboard?.writeText(g.code);const share=document.createElement('button');share.className='btn';share.style.cssText='width:100%;margin-top:8px';share.textContent='Delen via telefoon';share.onclick=async()=>{if(!navigator.share)return navigator.clipboard?.writeText(g.link);try{await navigator.share({title:'MMS Secure Guest',text:'Open deze beveiligde MMS-link. De toegangscode stuur ik apart.',url:g.link})}catch{}};const sc=document.createElement('div');sc.className='notice';sc.textContent='Safety code: '+g.safety;const done=document.createElement('button');done.className='btn';done.style.cssText='width:100%';done.textContent='Klaar';done.onclick=()=>modal.classList.add('hidden');modal.append(w,l1,box1,cp1,l2,box2,cp2,share,sc,done);modal.classList.remove('hidden')}
async function showInvite(){const a=await idbGet('accounts',session.id),code=encodeInvite();modal.innerHTML='<h2>Jouw MMS invite</h2><p>Deel deze code via een ander vertrouwd kanaal. Er staat geen telefoonnummer of privésleutel in.</p>';const cb=document.createElement('div');cb.className='codebox';const raw=decodeInvite(code);raw.label=a.label;const pub=session.vault.public;const fixed='MMS4.'+B64.url(TE.encode(JSON.stringify({...raw,label:a.label})));cb.textContent=fixed;const copy=document.createElement('button');copy.className='btn primary';copy.style.cssText='width:100%;margin-top:10px';copy.textContent='Kopieer invite';copy.onclick=()=>navigator.clipboard?.writeText(fixed);const close=document.createElement('button');close.className='btn';close.style.cssText='width:100%;margin-top:8px';close.textContent='Sluiten';close.onclick=()=>modal.classList.add('hidden');modal.append(cb,copy,close);modal.classList.remove('hidden')}
async function showSecurity(){const a=await idbGet('accounts',session.id),v=await idbGet('vaults',session.id);modal.innerHTML='<h2>MMS Security State</h2>';const ok=document.createElement('div');ok.className='notice good';ok.textContent='Actief: AES-256-GCM encrypted vault, signed encrypted envelopes, X25519/ECDH shared secret, HKDF-SHA-256, per-message symmetric ratchet, key pinning, replay IDs en auto-lock.';const warn=document.createElement('div');warn.className='notice danger';warn.textContent='Nog geen eindrelease: deze versie gebruikt nog geen geaudite libsignal Double/Triple Ratchet. Telefoon-discovery is optioneel en niet nodig om een identiteit te maken.';const kv=document.createElement('div');kv.className='kv';const vals=[['Telefoonnummer','Niet vereist voor accountcreatie'],['Relay kent wachtwoord','NEE'],['Relay heeft private keys','NEE'],['Relay ziet plaintext chats','NEE'],['Secure Guest','Eenmalige claim + gesplitste capability'],['SMS plaintext fallback','UIT'],['Lokale KDF','PBKDF2-HMAC-SHA-256 / 600k'],['Vault','AES-256-GCM'],['Identity fingerprint',a.signFingerprint],['Vault ciphertext',Math.round((v?.box?.ct?.length||0)*.75)+' bytes']];for(const [k,val] of vals){const x=document.createElement('div');x.textContent=k;const y=document.createElement('div');y.textContent=val;kv.append(x,y)}const cp=document.createElement('button');cp.className='btn';cp.style.width='100%';cp.textContent='Wachtwoord wijzigen';cp.onclick=showPasswordChange;const close=document.createElement('button');close.className='btn';close.style.cssText='width:100%;margin-top:8px';close.textContent='Sluiten';close.onclick=()=>modal.classList.add('hidden');modal.append(ok,warn,kv,cp,close);modal.classList.remove('hidden')}
function showPasswordChange(){modal.innerHTML='<h2>Wachtwoord wijzigen</h2><p>De willekeurige 256-bit vault master key blijft hetzelfde; alleen de password-wrapper verandert.</p>';const old=field('Huidig wachtwoord','password',''),nw=field('Nieuw wachtwoord','password','minimaal 16 tekens'),nw2=field('Herhaal nieuw wachtwoord','password',''),e=document.createElement('div');e.className='error';const go=document.createElement('button');go.className='btn primary';go.style.width='100%';go.textContent='Wijzig';go.onclick=async()=>{try{if(nw.i.value!==nw2.i.value)throw new Error('Nieuwe wachtwoorden zijn niet gelijk.');await changePassword(old.i.value,nw.i.value);modal.classList.add('hidden')}catch(err){e.textContent=err.message}};modal.append(old.w,nw.w,nw2.w,e,go)}

$('addInviteBtn').onclick=async()=>{const e=$('contactError');e.textContent='';const b=$('addInviteBtn');b.disabled=true;try{await addPhoneContact($('inviteInput').value);$('inviteInput').value=''}catch(err){e.textContent=err.message==='not_found'?'Geen MMS-account gevonden voor dit nummer.':err.message}finally{b.disabled=false}};$('inviteCodeBtn').onclick=showInviteCodeAdder;
$('composer').addEventListener('submit',async ev=>{ev.preventDefault();const i=$('messageInput'),text=i.value;i.value='';try{await sendMessage(text)}catch(err){i.value=text;alert('MMS blokkeerde/verloor het bericht: '+err.message)}});
$('lockBtn').onclick=lock;$('inviteBtn').onclick=showInvite;$('guestBtn').onclick=showGuestCreator;$('securityBtn').onclick=showSecurity;$('mobileLockBtn').onclick=lock;$('mobileInviteBtn').onclick=showMobileContactActions;$('mobileBackBtn').onclick=showMobileChats;$('mobileChatsBtn').onclick=showMobileChats;$('mobileGuestBtn').onclick=()=>{setMobileNav('guest');showGuestCreator()};$('mobileSecurityBtn').onclick=()=>{setMobileNav('security');showSecurity()};mobileMQ.addEventListener?.('change',e=>{if(!e.matches)document.body.classList.remove('mobile-chat')});
['pointerdown','keydown','mousemove','touchstart'].forEach(ev=>addEventListener(ev,()=>{if(session.master&&now()-session.lastActivity>1500)touch()},{passive:true}));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&session.master)setTimeout(()=>{if(document.hidden)lock()},30_000)});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;syncInstallUI()});
window.addEventListener('appinstalled',()=>{installPrompt=null;syncInstallUI();modal.classList.add('hidden')});
$('installBtn').onclick=requestInstall;$('mobileInstallBtn').onclick=requestInstall;
matchMedia('(display-mode: standalone)').addEventListener?.('change',syncInstallUI);addEventListener('online',relayHealth);addEventListener('offline',()=>{const r=$('relayState');r?.classList.remove('ok');const s=r?.querySelector('span');if(s)s.textContent='offline'});

(async()=>{if(!crypto?.subtle||!indexedDB){document.body.textContent='Deze browser mist vereiste Web Crypto/IndexedDB ondersteuning.';return}db=await openDB();if('serviceWorker' in navigator)navigator.serviceWorker.register(atBase('/sw.js'),{scope:BASE+'/'}).catch(()=>{});syncInstallUI();await relayHealth();await renderGate();renderLocked()})().catch(e=>{gate.innerHTML='<div class="card"><h2>MMS kon niet starten</h2><p>'+String(e.message||e)+'</p></div>'});
