'use strict';
import { TE, TD, B64, rand, concat, sha256, hmac, aesKey, hkdf, newId, verifyBytes, verifyBundle } from './crypto-core.js';

const $=id=>document.getElementById(id),now=()=>Date.now();
const BASE=new URL('.',location.href).pathname.replace(/\/$/,'');
const atBase=p=>BASE+(p.startsWith('/')?p:'/'+p);
const API_BASE='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms';
const inviteId=new URL(location.href).searchParams.get('i')||'';
const fragment=new URLSearchParams(location.hash.slice(1)),linkEncoded=fragment.get('a')||'';
let state=null,pollTimer=null,chats=[];

async function api(path,opt={}){const r=await fetch(API_BASE+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}
function validId(s){return /^[A-Za-z0-9_-]{16,80}$/.test(s||'')}
function canonicalGuestHead(e){return JSON.stringify({v:5,inviteId,id:e.id,dir:e.dir,n:e.n,ts:e.ts,iv:e.iv})}
async function guestSecret(linkPart,codePart){return hkdf(concat(linkPart,codePart),await sha256('MMS-GUEST-SECRET|'+inviteId),'MMS-GUEST-SECRET-V1|'+inviteId)}
async function guestAuthToken(secret){return B64.url(await hkdf(secret,await sha256('MMS-GUEST-AUTH|'+inviteId),'MMS-GUEST-AUTH-V1|'+inviteId))}
async function initialRatchets(secret){const salt=await sha256('MMS-GUEST-DIRECTION|'+inviteId);return{send:B64.enc(await hkdf(secret,salt,'MMS-GUEST-CHAIN|guest>owner')),sendN:0,recv:B64.enc(await hkdf(secret,salt,'MMS-GUEST-CHAIN|owner>guest')),recvN:0}}
async function nextChain(chain){return hmac(chain,'MMS-V5-GUEST-NEXT')}
async function msgKey(chain,n){return hmac(chain,'MMS-V5-GUEST-MESSAGE|'+n)}
async function safety(secret){const d=await sha256(concat(TE.encode('MMS-GUEST-SAFETY|'),secret));return[...d.slice(0,12)].map(x=>x.toString().padStart(3,'0')).join(' ').match(/.{1,15}/g).join(' · ')}
function decodeCode(v){const raw=(v||'').trim().replace(/-/g,'');if(!/^[A-Za-z0-9_-]{20,30}$/.test(raw))throw new Error('Ongeldige toegangscode.');return B64.unurl(raw)}
function setStatus(text,ok=false){const e=$('guestStatus');e.classList.toggle('ok',ok);e.querySelector('span').textContent=text}
function showError(msg){$('guestNotice').className='notice danger';$('guestNotice').textContent=msg}
function renderChats(){const el=$('guestMessages');el.innerHTML='';if(!chats.length){el.innerHTML='<div class="empty"><h2>Secure Guest</h2><p>Berichten worden uitsluitend in deze tab ontsleuteld.</p></div>';return}for(const m of chats){const b=document.createElement('div');b.className='bubble '+m.dir;b.append(document.createTextNode(m.text));const meta=document.createElement('div');meta.className='meta';meta.textContent=(m.dir==='out'?'Jij':'MMS')+' · '+new Date(m.ts).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · #'+m.n;b.append(meta);el.append(b)}el.scrollTop=el.scrollHeight}
async function receive(env){if(!state||env?.v!==5||env.dir!=='owner>guest'||!env.id)throw new Error('invalid_guest_message');if(state.seen.has(env.id))return;const rat=state.rat;if(env.n<rat.recvN){state.seen.add(env.id);return}if(env.n-rat.recvN>100)throw new Error('ratchet_gap');const aad=canonicalGuestHead(env),ct=B64.dec(env.ct),ok=await verifyBytes(state.owner.signPub,state.owner.signAlg,B64.dec(env.sig),concat(TE.encode(aad),ct));if(!ok)throw new Error('signature_failed');let chain=B64.dec(rat.recv),n=rat.recvN;while(n<env.n){chain=await nextChain(chain);n++}const key=await msgKey(chain,env.n),k=await aesKey(key);let pt;try{pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:B64.dec(env.iv),additionalData:TE.encode(aad),tagLength:128},k,ct)}catch{throw new Error('decrypt_failed')}let payload;try{payload=JSON.parse(TD.decode(pt))}catch{throw new Error('bad_payload')}if(payload.t!=='msg'||typeof payload.text!=='string')throw new Error('unsupported_payload');rat.recv=B64.enc(await nextChain(chain));rat.recvN=env.n+1;state.seen.add(env.id);if(payload.label)$('ownerName').textContent=payload.label;chats.push({id:env.id,dir:'in',text:payload.text,ts:env.ts,n:env.n});renderChats()}
async function send(text){text=text.trim();if(!state||!text)return;if(state.expiresAt<=now())throw new Error('Deze guest-sessie is verlopen.');const rat=state.rat,n=rat.sendN,chain=B64.dec(rat.send),key=await msgKey(chain,n),iv=rand(12),id=newId(18),ts=now(),head={v:5,id,dir:'guest>owner',n,ts,iv:B64.enc(iv)},aad=canonicalGuestHead(head),k=await aesKey(key),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:TE.encode(aad),tagLength:128},k,TE.encode(JSON.stringify({t:'msg',text})))),env={...head,ct:B64.enc(ct)};await api('/api/guest/send/'+encodeURIComponent(inviteId),{method:'POST',headers:{Authorization:'Bearer '+state.sessionToken},body:JSON.stringify({envelope:env})});rat.send=B64.enc(await nextChain(chain));rat.sendN=n+1;chats.push({id,dir:'out',text,ts,n});renderChats()}
async function poll(){if(!state)return;try{const r=await api('/api/guest/inbox/'+encodeURIComponent(inviteId),{headers:{Authorization:'Bearer '+state.sessionToken}});for(const env of r.items||[])await receive(env);updateExpiry();setStatus('E2EE verbonden',true)}catch(e){if(e.message==='unauthorized'){stop();showError('De guest-sessie is verlopen of ingetrokken.');$('guestInput').disabled=true;$('guestSend').disabled=true}else setStatus('verbinding opnieuw proberen…')}}
function stop(){if(pollTimer)clearInterval(pollTimer);pollTimer=null}
function updateExpiry(){if(!state)return;const left=Math.max(0,state.expiresAt-now()),m=Math.ceil(left/60000);$('guestExpiry').textContent=left?'Verloopt over ongeveer '+m+' min':'Verlopen';if(!left){$('guestInput').disabled=true;$('guestSend').disabled=true;stop()}}
async function claim(code){if(!validId(inviteId)||!linkEncoded)throw new Error('Deze Secure Guest-link is ongeldig of mist het geheime linkdeel.');const linkPart=B64.unurl(linkEncoded),codePart=decodeCode(code),secret=await guestSecret(linkPart,codePart),authToken=await guestAuthToken(secret);const r=await api('/api/guest/claim/'+encodeURIComponent(inviteId),{method:'POST',headers:{Authorization:'Bearer '+authToken},body:'{}'});if(!r.owner||!(await verifyBundle(r.owner)))throw new Error('De MMS-afzender heeft een ongeldige identity-bundle.');state={secret,sessionToken:r.sessionToken,owner:r.owner,expiresAt:r.expiresAt,rat:await initialRatchets(secret),seen:new Set()};history.replaceState(null,'',atBase('/guest.html')+'?i='+encodeURIComponent(inviteId));$('guestSafety').textContent='Safety '+await safety(secret);$('guestGate').classList.add('hidden');$('guestChat').classList.remove('hidden');$('guestNotice').className='notice good';$('guestNotice').textContent='E2EE actief. De toegangscode en guest-sleutel worden niet persistent opgeslagen. Sluit je deze tab, dan eindigt jouw lokale toegang.';for(const env of r.items||[])await receive(env);renderChats();updateExpiry();setStatus('E2EE verbonden',true);pollTimer=setInterval(poll,1800)}
function renderGate(){const g=$('guestGate');g.innerHTML='';if(!validId(inviteId)||!linkEncoded){showError('Deze uitnodigingslink is onvolledig. Vraag de afzender om een nieuwe MMS Secure Guest-link.');return}const c=document.createElement('div');c.className='card guestCard';c.innerHTML='<h2>Voer de aparte toegangscode in</h2><p>De link alleen is bewust niet genoeg. De afzender moet de toegangscode via een ander kanaal met je delen.</p>';const lab=document.createElement('label');lab.textContent='MMS Guest toegangscode';const i=document.createElement('input');i.placeholder='xxxx-xxxx-xxxx-xxxx…';i.autocomplete='off';const e=document.createElement('div');e.className='error';const b=document.createElement('button');b.className='btn primary';b.textContent='Open beveiligd gesprek';b.onclick=async()=>{e.textContent='';b.disabled=true;try{await claim(i.value)}catch(err){e.textContent=err.message;b.disabled=false}};i.onkeydown=ev=>{if(ev.key==='Enter')b.click()};c.append(lab,i,e,b);g.append(c);setTimeout(()=>i.focus(),0)}

$('guestComposer').addEventListener('submit',async ev=>{ev.preventDefault();const i=$('guestInput'),text=i.value;i.value='';try{await send(text)}catch(e){i.value=text;showError(e.message)}});
addEventListener('pagehide',()=>{if(state){state.secret.fill?.(0);state=null}stop()});
renderGate();
