'use strict';

(()=>{
const CORE='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms';
const CALL='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms-call';
const BUILD='0.14.0-e2ee-call-signaling';
const KEY_DB='MMS_CALL_KEYS_V1',KEY_STORE='keys',PIN_PREFIX='mms_callkey_pin_';
let selfId='',mailboxToken='',incomingPoll=null,signalPoll=null,active=null,lastIncoming='',keyDbPromise=null,ownRegisterPromise=null;
const peerKeyCache=new Map();
const upstreamFetch=window.fetch.bind(window);
const TE=new TextEncoder(),TD=new TextDecoder();

function reqUrl(input){return typeof input==='string'?input:(input?.url||'')}
function headersOf(input,init){const h=new Headers(input instanceof Request?input.headers:undefined);new Headers(init?.headers||{}).forEach((v,k)=>h.set(k,v));return h}
function parseBody(init){try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}}
window.fetch=async function(input,init={}){const url=reqUrl(input);try{const h=headersOf(input,init),a=h.get('authorization')||'';if(url.startsWith(CORE)&&a.startsWith('Bearer ')){mailboxToken=a.slice(7);const m=url.match(/\/api\/inbox\/([^/?#]+)/);if(m)selfId=decodeURIComponent(m[1]);const b=parseBody(init);if(!selfId&&b)selfId=b.requesterId||b.ownerId||b.from||b.id||'';ready()}}catch{}return upstreamFetch(input,init)};

function auth(){return{'Authorization':'Bearer '+mailboxToken,'Content-Type':'application/json'}}
async function req(base,path,opt={}){const r=await upstreamFetch(base+path,{...opt,headers:{...(opt.headers||{}),...(mailboxToken?auth():{'Content-Type':'application/json'})},cache:'no-store'});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b}
function e(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x}
function short(id){return id?('MMS '+id.slice(0,8)+'…'):'MMS-contact'}
function trusted(id){return !!window.MMS_SECURITY2?.isTrusted?.(id)}
function validId(id){return typeof id==='string'&&/^[A-Za-z0-9_-]{16,80}$/.test(id)}
function human(err){const m=err?.message||String(err);if(err?.name==='NotAllowedError')return'Microfoontoegang is geweigerd.';if(m.includes('SECURITY_'))return'Beveiliging blokkeerde deze identiteit. Controleer Security.';if(m==='untrusted_peer')return'Dit contact is nog niet via de identity-keylog geverifieerd.';if(m==='CALL_KEY_CHANGED')return'De call-key van dit contact is onverwacht gewijzigd. De oproep is geblokkeerd.';if(m==='call_key_not_found')return'Dit contact heeft de nieuwe beveiligde belfunctie nog niet geactiveerd.';if(m==='call_rate_limited')return'Te veel belpogingen. Probeer later opnieuw.';if(m==='recipient_not_found'||m==='not_found')return'Dit MMS-contact is niet bereikbaar.';if(m==='call_signal_decrypt_failed')return'De versleutelde oproepsignaling kon niet worden geverifieerd. Oproep geblokkeerd.';return m}
function supports(){return !!(window.RTCPeerConnection&&navigator.mediaDevices?.getUserMedia&&crypto?.subtle&&indexedDB)}
function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(stable).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}'}
async function shaHex(s){return[...new Uint8Array(await crypto.subtle.digest('SHA-256',TE.encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
function b64u(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const r=atob(s),o=new Uint8Array(r.length);for(let i=0;i<r.length;i++)o[i]=r.charCodeAt(i);return o}
function rand(n){const x=new Uint8Array(n);crypto.getRandomValues(x);return x}

function openKeyDb(){if(keyDbPromise)return keyDbPromise;keyDbPromise=new Promise((res,rej)=>{const r=indexedDB.open(KEY_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(KEY_STORE))r.result.createObjectStore(KEY_STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return keyDbPromise}
async function keyGet(id){const d=await openKeyDb();return new Promise((res,rej)=>{const r=d.transaction(KEY_STORE,'readonly').objectStore(KEY_STORE).get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function keyPut(v){const d=await openKeyDb();return new Promise((res,rej)=>{const r=d.transaction(KEY_STORE,'readwrite').objectStore(KEY_STORE).put(v);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})}
async function createOwnCallKey(id){const pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const publicJwk=await crypto.subtle.exportKey('jwk',pair.publicKey),privateJwk=await crypto.subtle.exportKey('jwk',pair.privateKey),privateKey=await crypto.subtle.importKey('jwk',privateJwk,{name:'ECDH',namedCurve:'P-256'},false,['deriveBits']),keyHash=await shaHex(stable(publicJwk));const rec={id,alg:'P-256',privateKey,publicJwk,keyHash,createdAt:Date.now()};await keyPut(rec);return rec}
async function ownKey(){if(!selfId)throw new Error('identity_not_ready');let k=await keyGet(selfId);if(!k?.privateKey||!k?.publicJwk)k=await createOwnCallKey(selfId);return k}
async function registerOwnKey(){if(!selfId||!mailboxToken)return;if(ownRegisterPromise)return ownRegisterPromise;ownRegisterPromise=(async()=>{const k=await ownKey();const r=await req(CALL,'/key/register',{method:'POST',body:JSON.stringify({profileId:selfId,alg:k.alg,publicJwk:k.publicJwk,keyHash:k.keyHash})});if(r.keyHash!==k.keyHash)throw new Error('own_call_key_registration_mismatch');return k})().catch(e=>{ownRegisterPromise=null;throw e});return ownRegisterPromise}
function pinKey(id){return PIN_PREFIX+id}
function readPin(id){try{return JSON.parse(localStorage.getItem(pinKey(id))||'null')}catch{return null}}
function writePin(id,v){localStorage.setItem(pinKey(id),JSON.stringify(v))}
async function verifyCallKeyHistory(id,key,history){if(!Array.isArray(history)||!history.length)throw new Error('call_key_history_missing');let prev='GENESIS',seq=0;for(const row of history){if(row.key_seq!==seq+1||row.prev_hash!==prev||typeof row.canonical_payload!=='string')throw new Error('call_key_history_invalid');const calc=await shaHex(row.prev_hash+'\n'+row.canonical_payload);if(calc!==row.entry_hash)throw new Error('call_key_history_hash_mismatch');let p;try{p=JSON.parse(row.canonical_payload)}catch{throw new Error('call_key_history_payload_invalid')}if(p.profileId!==id||p.keyHash!==row.key_hash)throw new Error('call_key_history_payload_mismatch');prev=row.entry_hash;seq=row.key_seq}const last=history[history.length-1],local=readPin(id);if(last.key_hash!==key.key_hash)throw new Error('call_key_history_head_mismatch');if(local){if(local.seq>last.key_seq)throw new Error('call_key_history_rollback');const at=history.find(x=>x.key_seq===local.seq);if(!at||at.entry_hash!==local.entryHash||local.keyHash!==key.key_hash)throw new Error('CALL_KEY_CHANGED')}writePin(id,{keyHash:key.key_hash,seq:last.key_seq,entryHash:last.entry_hash,verifiedAt:Date.now()});return last}
async function peerCallKey(id){if(peerKeyCache.has(id))return peerKeyCache.get(id);if(!trusted(id))throw new Error('untrusted_peer');const r=await req(CALL,'/key/'+encodeURIComponent(id)+'?requester='+encodeURIComponent(selfId)),key=r.key;if(!key||key.alg!=='P-256'||!key.public_jwk)throw new Error('call_key_not_found');const computed=await shaHex(stable(key.public_jwk));if(computed!==key.key_hash)throw new Error('call_key_hash_mismatch');await verifyCallKeyHistory(id,key,r.history);const publicKey=await crypto.subtle.importKey('jwk',key.public_jwk,{name:'ECDH',namedCurve:'P-256'},false,[]),out={...key,publicKey};peerKeyCache.set(id,out);return out}
async function resolvePeer(id){if(!validId(id))throw new Error('Geen geldig MMS-contact.');if(id===selfId)throw new Error('Je kunt jezelf niet bellen.');await req(CORE,'/api/profile/'+encodeURIComponent(id));if(!trusted(id))throw new Error('untrusted_peer');await peerCallKey(id);return id}
async function signalKey(peerId,callId){await registerOwnKey();const mine=await ownKey(),peer=await peerCallKey(peerId),bits=new Uint8Array(await crypto.subtle.deriveBits({name:'ECDH',public:peer.publicKey},mine.privateKey,256)),base=await crypto.subtle.importKey('raw',bits,'HKDF',false,['deriveKey']),ids=[selfId,peerId].sort().join('|'),salt=new Uint8Array(await crypto.subtle.digest('SHA-256',TE.encode('MMS-CALL-HKDF-SALT-V1|'+ids))),info=TE.encode('MMS-CALL-SIGNAL-V1|'+callId);return crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt,info},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function signalAad(callId,kind,from,to){return JSON.stringify({v:1,callId,kind,from,to})}
async function sealSignal(peerId,callId,kind,payload){const key=await signalKey(peerId,callId),iv=rand(12),aad=signalAad(callId,kind,selfId,peerId),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:TE.encode(aad),tagLength:128},key,TE.encode(JSON.stringify(payload))));return{v:1,iv:b64u(iv),ct:b64u(ct)}}
async function openSignal(peerId,callId,kind,blob){try{const key=await signalKey(peerId,callId),aad=signalAad(callId,kind,peerId,selfId),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64u(blob.iv),additionalData:TE.encode(aad),tagLength:128},key,unb64u(blob.ct));return JSON.parse(TD.decode(pt))}catch(e){console.error('MMS call signal decrypt rejected',e);throw new Error('call_signal_decrypt_failed')}}

function layer(){let l=document.getElementById('mmsCallLayer');if(!l){l=e('div','mmsCallLayer');l.id='mmsCallLayer';document.body.append(l)}return l}function hide(){const l=layer();l.classList.add('hidden');l.replaceChildren()}function show(){layer().classList.remove('hidden')}
function style(){if(document.getElementById('mmsCallStyle'))return;const s=document.createElement('style');s.id='mmsCallStyle';s.textContent=`.mmsCallLayer{position:fixed;inset:0;z-index:140;background:rgba(2,8,6,.9);backdrop-filter:blur(22px);display:grid;place-items:center;padding:16px}.mmsCallLayer.hidden{display:none}.mmsCallCard{width:min(430px,100%);background:#0b1813;border:1px solid #315747;border-radius:28px;padding:26px;text-align:center;box-shadow:0 30px 90px #0009}.mmsCallAvatar{width:88px;height:88px;border-radius:30px;margin:0 auto 16px;background:#62e6ae;color:#042117;display:grid;place-items:center;font-size:34px;font-weight:900}.mmsCallName{font-size:23px;font-weight:900}.mmsCallStatus{color:#9ab8ad;margin:8px 0 16px}.mmsCallCode{border:1px solid #315747;background:#07110e;border-radius:14px;padding:12px;margin:12px 0;font:800 18px/1.5 ui-monospace,monospace;letter-spacing:.04em}.mmsCallHint{font-size:11px;color:#8aa79c;line-height:1.5}.mmsCallActions{display:flex;justify-content:center;gap:18px;margin-top:20px}.mmsCallRound{width:62px;height:62px;border-radius:50%;border:1px solid #315747;background:#102019;color:#eef9f5;font-size:23px;cursor:pointer}.mmsCallRound.primary{background:#62e6ae;color:#042117;border:0}.mmsCallRound.danger{background:#d95050;color:white;border:0}.mmsCallField{text-align:left;margin:16px 0}.mmsCallField input{width:100%;box-sizing:border-box;border:1px solid #29463b;background:#07110e;color:#eef9f5;border-radius:12px;padding:12px}.mmsCallRow{display:flex;gap:8px}.mmsCallRow button{flex:1}.mmsCallError{color:#ffaaaa;min-height:18px;font-size:11px}.mmsCallLabel{font-size:10px;color:#8aa79c;margin-top:5px}`;document.head.append(s)}
function buttonWrap(btn,label){const w=e('div');w.append(btn,e('div','mmsCallLabel',label));return w}
function installButtons(){style();let b=document.getElementById('mmsCallBtn');if(!b){b=e('button','btn','☎ Bellen');b.id='mmsCallBtn';b.onclick=dialer;document.querySelector('.actions')?.insertBefore(b,document.getElementById('guestBtn')||null)}let m=document.getElementById('mmsMobileCallBtn');if(!m){m=e('button','iconBtn','☎');m.id='mmsMobileCallBtn';m.setAttribute('aria-label','Bellen');m.onclick=dialer;document.querySelector('.mobileTopActions')?.insertBefore(m,document.getElementById('mobileLockBtn')||null)}b.disabled=!mailboxToken;m.disabled=!mailboxToken}
function ready(){installButtons();registerOwnKey().catch(e=>console.warn('MMS call-key registration:',e.message));if(!incomingPoll)incomingPoll=setInterval(checkIncoming,1800);checkIncoming()}
async function mic(){return navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})}
function waitIce(pc,ms=9000){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(res=>{let done=false;const f=()=>{if(!done&&pc.iceGatheringState==='complete'){done=true;pc.removeEventListener('icegatheringstatechange',f);res()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(()=>{if(!done){done=true;pc.removeEventListener('icegatheringstatechange',f);res()}},ms)})}
function peer(stream){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}],iceCandidatePoolSize:2});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=ev=>{let a=document.getElementById('mmsRemoteAudio');if(!a){a=document.createElement('audio');a.id='mmsRemoteAudio';a.autoplay=true;a.playsInline=true;document.body.append(a)}a.srcObject=ev.streams[0];a.play?.().catch(()=>{})};pc.onconnectionstatechange=()=>{if(!active||active.pc!==pc)return;if(pc.connectionState==='connected')setStatus('Verbonden — signaling E2EE');if(['failed','disconnected'].includes(pc.connectionState))setStatus('Verbinding onderbroken')};return pc}
function fp(desc){const m=desc?.sdp?.match(/a=fingerprint:sha-256\s+([A-F0-9:]+)/i);return m?m[1].toUpperCase():''}
async function safetyCode(pc,callId){const a=fp(pc.localDescription),b=fp(pc.remoteDescription);if(!a||!b)return'';const src=['MMS-CALL-SAS-V1',callId,...[a,b].sort()].join('|');const d=new Uint8Array(await crypto.subtle.digest('SHA-256',TE.encode(src)));return[...d.slice(0,6)].map(x=>x.toString().padStart(3,'0')).join(' ')}
async function refreshCode(){if(!active)return;const code=await safetyCode(active.pc,active.id),c=document.getElementById('mmsCallCode');if(c)c.textContent=code||'code nog niet beschikbaar'}function setStatus(s){const n=document.getElementById('mmsCallStatus');if(n)n.textContent=s}
function callScreen(peerId,status){const l=layer();l.replaceChildren();const c=e('div','mmsCallCard');c.append(e('div','mmsCallAvatar','M'),e('div','mmsCallName',short(peerId)));const st=e('div','mmsCallStatus',status);st.id='mmsCallStatus';c.append(st);const code=e('div','mmsCallCode','code wordt opgebouwd…');code.id='mmsCallCode';c.append(code,e('div','mmsCallHint','Offer/answer zijn end-to-end versleuteld. Vergelijk deze DTLS safety-code voor extra verificatie tegen een kwaadwillende eerste-contactserver.'));const acts=e('div','mmsCallActions'),mute=e('button','mmsCallRound','🎙'),hang=e('button','mmsCallRound danger','✕');mute.onclick=()=>{if(!active)return;active.muted=!active.muted;active.stream.getAudioTracks().forEach(t=>t.enabled=!active.muted);mute.textContent=active.muted?'🔇':'🎙'};hang.onclick=()=>endCall(true);acts.append(buttonWrap(mute,'Mute'),buttonWrap(hang,'Ophangen'));c.append(acts);l.append(c);show()}
function dialer(){if(!mailboxToken||!selfId)return alert('Ontgrendel eerst je MMS-identiteit.');const l=layer();l.replaceChildren();const c=e('div','mmsCallCard');c.append(e('div','mmsCallAvatar','☎'),e('div','mmsCallName','E2EE MMS-bellen'),e('div','mmsCallStatus','Bel een keylog-gepind MMS-contact.'));const f=e('div','mmsCallField'),i=document.createElement('input');i.placeholder='+316… of MMS-ID';i.autocomplete='off';f.append(i);const er=e('div','mmsCallError'),row=e('div','mmsCallRow'),cancel=e('button','btn','Annuleren'),go=e('button','btn primary','Bel');cancel.onclick=hide;go.onclick=async()=>{go.disabled=true;er.textContent='';try{await registerOwnKey();let id=i.value.trim();if(id.startsWith('+')){const r=await req(CORE,'/api/discover',{method:'POST',body:JSON.stringify({requesterId:selfId,phone:id})});id=r.profile?.id||''}id=await resolvePeer(id);await outgoing(id)}catch(x){er.textContent=human(x);go.disabled=false}};i.onkeydown=x=>{if(x.key==='Enter')go.click()};row.append(cancel,go);c.append(f,er,row,e('div','mmsCallHint','WebRTC-audio is versleuteld. SDP/ICE offer en answer worden daarnaast met een per-call ECDH/HKDF/AES-256-GCM sleutel versleuteld voordat ze naar de relay gaan.'));l.append(c);show();setTimeout(()=>i.focus(),0)}
async function outgoing(peerId){if(!supports())throw new Error('Bellen wordt niet ondersteund op dit apparaat.');if(active)throw new Error('Er is al een oproep actief.');let stream,pc;try{await peerCallKey(peerId);stream=await mic();pc=peer(stream);const id=crypto.randomUUID().replace(/-/g,'')+Math.random().toString(36).slice(2,8);active={id,peer:peerId,stream,pc,direction:'out',muted:false};callScreen(peerId,'Bellen…');const offer=await pc.createOffer({offerToReceiveAudio:true});await pc.setLocalDescription(offer);await waitIce(pc);const signal=await sealSignal(peerId,id,'offer',pc.localDescription);await req(CALL,'/start',{method:'POST',body:JSON.stringify({callerId:selfId,calleeId:peerId,callId:id,signal})});startSignals()}catch(x){try{stream?.getTracks().forEach(t=>t.stop());pc?.close()}catch{}active=null;hide();throw x}}
async function checkIncoming(){if(!mailboxToken||!selfId||active||document.hidden)return;try{await registerOwnKey();const r=await req(CALL,'/incoming/'+encodeURIComponent(selfId)),c=r.calls?.[0];if(!c||c.id===lastIncoming)return;lastIncoming=c.id;try{await req(CORE,'/api/profile/'+encodeURIComponent(c.caller_id));if(!trusted(c.caller_id))throw new Error('untrusted_peer');await peerCallKey(c.caller_id)}catch(e){await req(CALL,'/decline/'+encodeURIComponent(c.id),{method:'POST',body:JSON.stringify({calleeId:selfId})}).catch(()=>{});console.warn('MMS Security 2 blocked caller',e.message);return}incoming(c)}catch{}}
function incoming(call){const l=layer();l.replaceChildren();const c=e('div','mmsCallCard');c.append(e('div','mmsCallAvatar','☎'),e('div','mmsCallName',short(call.caller_id)),e('div','mmsCallStatus','Inkomende E2EE MMS-oproep'));const a=e('div','mmsCallActions'),no=e('button','mmsCallRound danger','✕'),yes=e('button','mmsCallRound primary','☎');no.onclick=()=>decline(call);yes.onclick=()=>answer(call);a.append(buttonWrap(no,'Weiger'),buttonWrap(yes,'Neem op'));c.append(a);l.append(c);show();navigator.vibrate?.([160,80,160])}
async function answer(call){let stream,pc;try{const sigs=await req(CALL,'/signals/'+encodeURIComponent(call.id)+'?id='+encodeURIComponent(selfId)),blob=sigs.signals?.find(x=>x.kind==='offer')?.payload;if(!blob)throw new Error('Oproepdata ontbreekt.');const offer=await openSignal(call.caller_id,call.id,'offer',blob);stream=await mic();pc=peer(stream);active={id:call.id,peer:call.caller_id,stream,pc,direction:'in',muted:false};callScreen(call.caller_id,'Verbinden…');await pc.setRemoteDescription(offer);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);await refreshCode();const signal=await sealSignal(call.caller_id,call.id,'answer',pc.localDescription);await req(CALL,'/answer/'+encodeURIComponent(call.id),{method:'POST',body:JSON.stringify({calleeId:selfId,signal})});startSignals()}catch(x){try{stream?.getTracks().forEach(t=>t.stop());pc?.close()}catch{}active=null;hide();alert(human(x));await decline(call,true)}}
async function decline(call,silent=false){try{await req(CALL,'/decline/'+encodeURIComponent(call.id),{method:'POST',body:JSON.stringify({calleeId:selfId})})}catch{}hide();if(!silent)navigator.vibrate?.(25)}function startSignals(){stopSignals();signalPoll=setInterval(pollSignals,900);pollSignals()}function stopSignals(){if(signalPoll){clearInterval(signalPoll);signalPoll=null}}
async function pollSignals(){if(!active)return;try{const r=await req(CALL,'/signals/'+encodeURIComponent(active.id)+'?id='+encodeURIComponent(selfId));for(const s of r.signals||[]){if(s.kind==='answer'&&active.direction==='out'&&s.payload&&!active.pc.remoteDescription){const ans=await openSignal(active.peer,active.id,'answer',s.payload);await active.pc.setRemoteDescription(ans);await refreshCode();setStatus('Verbinden… · signaling E2EE')}else if(s.kind==='decline'){setStatus('Oproep geweigerd');setTimeout(()=>endCall(false),700)}else if(s.kind==='hangup'){setStatus('Gesprek beëindigd');setTimeout(()=>endCall(false),350)}}if(r.state==='missed'){setStatus('Geen antwoord');setTimeout(()=>endCall(false),700)}}catch(x){console.warn('MMS call signaling:',x?.message||x);if((x?.message||'').includes('decrypt')){setStatus('Signaling verificatie mislukt — geblokkeerd');setTimeout(()=>endCall(false),900)}}}
async function endCall(notify){const a=active;if(!a){hide();return}active=null;stopSignals();try{a.stream?.getTracks().forEach(t=>t.stop());a.pc?.close()}catch{}const ra=document.getElementById('mmsRemoteAudio');if(ra){ra.srcObject=null;ra.remove()}hide();if(notify&&mailboxToken)try{await req(CALL,'/hangup/'+encodeURIComponent(a.id),{method:'POST',body:JSON.stringify({id:selfId})})}catch{}}
window.addEventListener('pagehide',()=>{if(active)endCall(true)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{style();installButtons()});else{style();installButtons()}console.info('MMS Calls',BUILD);
})();
