'use strict';

import { TE, TD, B64, rand, concat, sha256, aesEnc, aesDec, deriveKEK } from './crypto-core.js?v=20260930-0930';

const ACCESS_BUILD='0.9.0-lock-contacts.1';
const MMS_DB='MMS_APP_V4';
const PBKDF2_ITERS=600_000;
let activeId=null;
let busy=false;

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const accessKey=id=>'mms_access_'+id;
const getAccess=id=>{try{return JSON.parse(localStorage.getItem(accessKey(id))||'null')}catch{return null}};
const setAccess=(id,v)=>localStorage.setItem(accessKey(id),JSON.stringify({id,...v}));
const delAccess=id=>localStorage.removeItem(accessKey(id));
const deviceLabel=()=>/iphone|ipad|ipod/i.test(navigator.userAgent)?'Face ID / Touch ID':'Biometrie / apparaatbeveiliging';
const generatedPassword=()=>B64.url(rand(32))+'!9a';

function injectStyle(){if(document.getElementById('mmsAccessStyle'))return;const s=document.createElement('style');s.id='mmsAccessStyle';s.textContent='.mmsAccessBox{margin:14px 0;padding:13px;border:1px solid #315747;background:#0b2119;border-radius:16px}.mmsAccessBox strong{display:block;margin-bottom:4px}.mmsAccessBox small{display:block;color:var(--muted);line-height:1.45}.mmsAccessChoices{display:grid;gap:8px;margin-top:10px}.mmsAccessChoice{display:flex;gap:10px;align-items:flex-start;border:1px solid var(--line);border-radius:13px;padding:10px;background:#08140f;cursor:pointer}.mmsAccessChoice input{width:auto;margin-top:3px}.mmsAccessChoice b{display:block;font-size:13px}.mmsAccessChoice span{display:block;color:var(--muted);font-size:10px;margin-top:2px;line-height:1.35}.mmsAccessActions{display:flex;gap:6px;align-items:center}.mmsAccessActions .btn{white-space:nowrap}.mmsAccessSection{border-top:1px solid var(--line);margin-top:14px;padding-top:14px}.mmsAccessSection .btn{width:100%;margin-top:8px}.mmsAccessBadge{display:inline-block;border:1px solid #315747;border-radius:999px;padding:3px 7px;font-size:9px;color:var(--accent);margin-top:5px}';document.head.appendChild(s)}

function openMmsDB(){return new Promise((res,rej)=>{const r=indexedDB.open(MMS_DB);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function allAccounts(){const d=await openMmsDB();return new Promise((res,rej)=>{const r=d.transaction('accounts').objectStore('accounts').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function vaultRecord(id){const d=await openMmsDB();return new Promise((res,rej)=>{const r=d.transaction('vaults').objectStore('vaults').get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function passwordValid(id,pw){const r=await vaultRecord(id);if(!r?.wrap)return false;try{const k=await deriveKEK(pw,B64.dec(r.wrap.salt),r.wrap.iters||PBKDF2_ITERS);await aesDec(k,r.wrap.wrapped,'MMS-V4-MASTER:'+id);return true}catch{return false}}

async function platformAuth(){try{return !!window.PublicKeyCredential&&await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()}catch{return false}}
async function prfKey(out){return sha256(concat(TE.encode('MMS-ACCESS-PRF-V1|'),new Uint8Array(out)))}
async function makeBiometric(label,secret){
  if(!(await platformAuth()))throw new Error('Op dit apparaat is geen geschikte Face ID/Touch ID of platform-authenticator beschikbaar.');
  const salt=rand(32),cred=await navigator.credentials.create({publicKey:{challenge:rand(32),rp:{name:'MMS',id:location.hostname},user:{id:rand(16),name:'mms-'+Date.now(),displayName:label||'MMS'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-8}],authenticatorSelection:{authenticatorAttachment:'platform',residentKey:'preferred',userVerification:'required'},timeout:60000,attestation:'none',extensions:{prf:{eval:{first:salt}}}}});
  if(!cred)throw new Error('Biometrische registratie is geannuleerd.');let out=cred.getClientExtensionResults?.()?.prf?.results?.first;
  if(!out){const a=await navigator.credentials.get({publicKey:{challenge:rand(32),rpId:location.hostname,allowCredentials:[{type:'public-key',id:cred.rawId}],userVerification:'required',timeout:60000,extensions:{prf:{eval:{first:salt}}}}});out=a?.getClientExtensionResults?.()?.prf?.results?.first}
  if(!out)throw new Error('Deze browser kan de MMS-vault nog niet cryptografisch aan Face ID/Touch ID koppelen. Kies voorlopig een wachtwoord.');
  const key=await prfKey(out),wrappedSecret=await aesEnc(key,secret,'MMS-ACCESS-SECRET-V1');return{mode:'biometric',credentialId:B64.url(new Uint8Array(cred.rawId)),prfSalt:B64.enc(salt),wrappedSecret};
}
async function biometricSecret(rec){const a=await navigator.credentials.get({publicKey:{challenge:rand(32),rpId:location.hostname,allowCredentials:[{type:'public-key',id:B64.unurl(rec.credentialId)}],userVerification:'required',timeout:60000,extensions:{prf:{eval:{first:B64.dec(rec.prfSalt)}}}}});if(!a)throw new Error('Biometrische ontgrendeling is geannuleerd.');const out=a.getClientExtensionResults?.()?.prf?.results?.first;if(!out)throw new Error('Face ID/Touch ID leverde geen vault-sleutel op.');return TD.decode(await aesDec(await prfKey(out),rec.wrappedSecret,'MMS-ACCESS-SECRET-V1'))}

async function waitFor(fn,timeout=8000){const end=Date.now()+timeout;while(Date.now()<end){const v=fn();if(v)return v;await sleep(40)}return null}
async function openWithSecret(original,id,secret){activeId=id;original();const p=await waitFor(()=>document.querySelector('#gate input[type="password"]'));if(!p)throw new Error('Ontgrendelscherm kon niet worden geopend.');p.value=secret;const b=[...document.querySelectorAll('#gate button')].find(x=>(x.textContent||'').trim()==='Ontgrendel');if(!b)throw new Error('Ontgrendelknop ontbreekt.');b.click()}

async function enhanceAccounts(){const list=document.querySelector('#gate .accounts');if(!list)return;const accounts=await allAccounts();for(const row of list.querySelectorAll('.account')){if(row.dataset.mmsAccess==='1')continue;row.dataset.mmsAccess='1';const sm=row.querySelector('small'),primary=row.querySelector('button');if(!sm||!primary)continue;const prefix=((sm.textContent||'').match(/MMS ID\s+([^…]+)/)||[])[1]||'',a=accounts.find(x=>x.id.startsWith(prefix));if(!a)continue;const original=primary.onclick;primary.onclick=()=>{activeId=a.id;original()};const rec=getAccess(a.id);if(!rec)continue;const actions=document.createElement('div');actions.className='mmsAccessActions';primary.remove();actions.append(primary);row.append(actions);if(rec.mode==='biometric'){primary.textContent=deviceLabel();primary.onclick=async()=>{primary.disabled=true;try{await openWithSecret(original,a.id,await biometricSecret(rec))}catch(e){alert(e.message||String(e))}finally{primary.disabled=false}};if(rec.userPassword){const p=document.createElement('button');p.className='btn';p.textContent='Wachtwoord';p.onclick=()=>{activeId=a.id;original()};actions.append(p)}}else if(rec.mode==='none'){primary.textContent='Open';primary.onclick=async()=>{primary.disabled=true;try{await openWithSecret(original,a.id,rec.secret)}catch(e){alert(e.message||String(e))}finally{primary.disabled=false}};if(rec.userPassword){const p=document.createElement('button');p.className='btn';p.textContent='Wachtwoord';p.onclick=()=>{activeId=a.id;original()};actions.append(p)}}}}

async function enhanceCreate(){const card=document.querySelector('#gate .card');if(!card||card.dataset.mmsAccessCreate==='1'||(card.querySelector('h2')?.textContent||'').trim()!=='Nieuwe MMS-identiteit')return;card.dataset.mmsAccessCreate='1';const fields=[...card.querySelectorAll('.field')],name=fields[0]?.querySelector('input'),pw=fields[1]?.querySelector('input'),pw2=fields[2]?.querySelector('input'),go=[...card.querySelectorAll('button')].find(x=>(x.textContent||'').trim()==='Maak identiteit');if(!name||!pw||!pw2||!go)return;const original=go.onclick,box=document.createElement('div');box.className='mmsAccessBox';box.innerHTML='<strong>Sessievergrendeling</strong><small>Kies hoe je MMS op dit apparaat wilt openen. Berichten blijven in alle gevallen E2EE.</small><div class="mmsAccessChoices"></div>';const choices=box.querySelector('.mmsAccessChoices'),opts=[['biometric',deviceLabel(),'Aanbevolen op telefoons. Je hoeft geen MMS-wachtwoord te onthouden.'],['biometric_password',deviceLabel()+' + wachtwoord','Ontgrendel later met biometrie of met je wachtwoord.'],['password','Wachtwoord','Vraag iedere nieuwe sessie om je MMS-wachtwoord.'],['none','Geen sessievergrendeling','Open MMS op dit apparaat zonder extra controle.']];for(const [v,t,d] of opts){const l=document.createElement('label');l.className='mmsAccessChoice';l.innerHTML='<input type="radio" name="mmsLockMode" value="'+v+'"><div><b>'+t+'</b><span>'+d+'</span></div>';choices.append(l)}card.insertBefore(box,fields[1]);const radios=[...box.querySelectorAll('input')];radios[0].checked=true;const sync=()=>{const mode=radios.find(r=>r.checked)?.value||'password',show=mode==='password'||mode==='biometric_password';fields[1].style.display=show?'':'none';fields[2].style.display=show?'':'none'};radios.forEach(r=>r.onchange=sync);sync();go.onclick=async()=>{const mode=radios.find(r=>r.checked)?.value||'password';if(mode==='password')return original();let secret,userPassword=false,prepared=null;if(mode==='biometric_password'){secret=pw.value;userPassword=true;if(secret.length<16||secret!==pw2.value){const e=card.querySelector('.error');if(e)e.textContent=secret!==pw2.value?'Wachtwoorden zijn niet gelijk.':'Gebruik minimaal 16 tekens.';return}}else secret=generatedPassword();go.disabled=true;const old=go.textContent;try{if(mode.startsWith('biometric')){go.textContent='Biometrie instellen…';prepared=await makeBiometric(name.value,secret)}const before=new Set((await allAccounts()).map(a=>a.id));pw.value=secret;pw2.value=secret;await original();let created=null;for(let i=0;i<100&&!created;i++){created=(await allAccounts()).find(a=>!before.has(a.id))||null;if(!created)await sleep(100)}if(created){activeId=created.id;if(mode==='none')setAccess(created.id,{mode:'none',secret,userPassword:false});else setAccess(created.id,{...prepared,userPassword})}}catch(e){const er=card.querySelector('.error');if(er)er.textContent=e.message||String(e);go.disabled=false;go.textContent=old}}}

async function activeAccount(){if(activeId)return (await allAccounts()).find(a=>a.id===activeId)||null;const label=document.getElementById('meName')?.textContent||'';return (await allAccounts()).find(a=>a.label===label)||null}
function form(title,copy){const m=document.getElementById('modal');m.innerHTML='<h2>'+title+'</h2><p>'+copy+'</p>';return m}
async function addBiometricExisting(a){const m=form('Face ID / Touch ID instellen','Voer één keer je huidige MMS-wachtwoord in. Daarna blijft dat wachtwoord ook als fallback beschikbaar.'),w=document.createElement('div');w.className='field';w.innerHTML='<label>Huidig wachtwoord</label><input type="password" autocomplete="current-password">';const e=document.createElement('div');e.className='error',go=document.createElement('button');go.className='btn primary';go.style.width='100%';go.textContent='Biometrie instellen';go.onclick=async()=>{e.textContent='';go.disabled=true;try{const secret=w.querySelector('input').value;if(!(await passwordValid(a.id,secret)))throw new Error('Huidig wachtwoord klopt niet.');setAccess(a.id,{...(await makeBiometric(a.label,secret)),userPassword:true});m.classList.add('hidden')}catch(err){e.textContent=err.message||String(err);go.disabled=false}};const close=document.createElement('button');close.className='btn';close.style.cssText='width:100%;margin-top:8px';close.textContent='Annuleren';close.onclick=()=>m.classList.add('hidden');m.append(w,e,go,close);m.classList.remove('hidden')}
async function noLockExisting(a){const m=form('Geen sessievergrendeling','Voer één keer je huidige MMS-wachtwoord in. Daarna opent MMS op dit apparaat zonder extra vraag.'),w=document.createElement('div');w.className='field';w.innerHTML='<label>Huidig wachtwoord</label><input type="password" autocomplete="current-password">';const e=document.createElement('div');e.className='error',go=document.createElement('button');go.className='btn primary';go.style.width='100%';go.textContent='Zet vergrendeling uit';go.onclick=async()=>{e.textContent='';go.disabled=true;try{const secret=w.querySelector('input').value;if(!(await passwordValid(a.id,secret)))throw new Error('Huidig wachtwoord klopt niet.');setAccess(a.id,{mode:'none',secret,userPassword:true});m.classList.add('hidden')}catch(err){e.textContent=err.message||String(err);go.disabled=false}};const close=document.createElement('button');close.className='btn';close.style.cssText='width:100%;margin-top:8px';close.textContent='Annuleren';close.onclick=()=>m.classList.add('hidden');m.append(w,e,go,close);m.classList.remove('hidden')}

async function enhanceSecurity(){const m=document.getElementById('modal');if(!m||m.classList.contains('hidden')||m.dataset.mmsAccessSecurity==='1'||(m.querySelector('h2')?.textContent||'').trim()!=='MMS Security State')return;m.dataset.mmsAccessSecurity='1';const a=await activeAccount();if(!a)return;const rec=getAccess(a.id),sec=document.createElement('div');sec.className='mmsAccessSection';sec.innerHTML='<strong>Sessievergrendeling</strong><div class="mmsAccessBadge">'+(rec?.mode==='biometric'?deviceLabel():rec?.mode==='none'?'Geen sessievergrendeling':'Wachtwoord')+'</div>';if(!rec){const b=document.createElement('button');b.className='btn primary';b.textContent=deviceLabel()+' toevoegen';b.onclick=()=>addBiometricExisting(a);sec.append(b);const n=document.createElement('button');n.className='btn';n.textContent='Geen sessievergrendeling';n.onclick=()=>noLockExisting(a);sec.append(n)}else if(rec.userPassword){const b=document.createElement('button');b.className='btn';b.textContent='Alleen wachtwoord gebruiken';b.onclick=()=>{delAccess(a.id);m.classList.add('hidden')};sec.append(b)}const close=m.lastElementChild;m.insertBefore(sec,close||null)}

async function inviteCode(){const b=document.getElementById('inviteBtn');if(!b||b.disabled)throw new Error('Ontgrendel eerst MMS.');b.click();const box=await waitFor(()=>document.querySelector('#modal .codebox'));if(!box)throw new Error('Invite kon niet worden gemaakt.');const code=box.textContent||'';document.getElementById('modal').classList.add('hidden');return code}
async function showContactInvite(){const code=await inviteCode(),text='Ik nodig je uit voor MMS — Mattheüs Messaging Service. Open https://opulenzo-create.github.io/ en voeg mij toe met deze MMS invite-code:\n\n'+code,m=document.getElementById('modal');m.innerHTML='<h2>Contact uitnodigen</h2><p>Je invite bevat alleen je publieke MMS-identiteit, geen privésleutel.</p>';if(navigator.contacts?.select){const pick=document.createElement('button');pick.className='btn primary';pick.style.width='100%';pick.textContent='Kies uit contacten';pick.onclick=async()=>{try{const cs=await navigator.contacts.select(['name','tel'],{multiple:false}),tel=cs?.[0]?.tel?.[0];if(tel)location.href='sms:'+encodeURIComponent(tel)+'?body='+encodeURIComponent(text)}catch(e){if(e.name!=='AbortError')alert(e.message||String(e))}};m.append(pick)}const share=document.createElement('button');share.className='btn primary';share.style.cssText='width:100%;margin-top:8px';share.textContent=/iphone|ipad|ipod/i.test(navigator.userAgent)?'Kies contact via Delen':'Delen via telefoon';share.onclick=async()=>{try{if(navigator.share)await navigator.share({title:'MMS uitnodiging',text});else{await navigator.clipboard.writeText(text);alert('Uitnodiging gekopieerd.')}}catch(e){if(e.name!=='AbortError')alert(e.message||String(e))}};m.append(share);const note=document.createElement('div');note.className='notice';note.textContent=/iphone|ipad|ipod/i.test(navigator.userAgent)?'Safari geeft webapps geen directe toegang tot je volledige iPhone-contactenlijst. Via Delen kun je wel Berichten, WhatsApp, Mail en een ontvanger kiezen.':'Als Contact Picker beschikbaar is, ziet MMS alleen de contacten die jij expliciet selecteert.';m.append(note);const close=document.createElement('button');close.className='btn';close.style.width='100%';close.textContent='Sluiten';close.onclick=()=>m.classList.add('hidden');m.append(close);m.classList.remove('hidden')}
function enhanceInvite(){const add=document.querySelector('.side .add');if(add&&!document.getElementById('inviteContactBtn')){const b=document.createElement('button');b.id='inviteContactBtn';b.className='btn';b.textContent='Nodig contact uit';b.onclick=()=>showContactInvite().catch(e=>alert(e.message||String(e)));const er=document.getElementById('contactError');add.insertBefore(b,er||null)}const b=document.getElementById('inviteContactBtn');if(b)b.disabled=document.getElementById('inviteCodeBtn')?.disabled??true;const m=document.getElementById('modal');if(m&&!m.classList.contains('hidden')&&(m.querySelector('h2')?.textContent||'').trim()==='Contact'&&!m.querySelector('[data-mms-invite-contact]')){const x=document.createElement('button');x.dataset.mmsInviteContact='1';x.className='btn primary';x.style.cssText='width:100%;margin-top:8px';x.textContent='Nodig iemand uit';x.onclick=()=>showContactInvite().catch(e=>alert(e.message||String(e)));m.insertBefore(x,m.lastElementChild||null)}}

async function enhance(){if(busy)return;busy=true;try{injectStyle();await enhanceAccounts();await enhanceCreate();await enhanceSecurity();enhanceInvite();const p=document.querySelector('#gate .card p[style*="font-size:10px"]');if(p&&!p.textContent.includes('Access'))p.textContent+=' · Access '+ACCESS_BUILD}catch(e){console.warn('MMS Access:',e)}finally{busy=false}}
const observer=new MutationObserver(()=>enhance());observer.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class','disabled']});addEventListener('DOMContentLoaded',enhance);setTimeout(enhance,0);setInterval(enhance,1200);
