'use strict';
import {TE,TD,B64,rand,concat,sha256,aesEnc,aesDec,deriveKEK,newId,fingerprintJwk,genKeys,signBundle} from './crypto-core.js?v=20261002-2031';

const BUILD='0.10.0-access-core';
const DB_NAME='MMS_APP_V4';
const API_BASE='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms';
const ITERS=600000;
let dbPromise=null,activeId=null,sessionSecret=null,pendingSecret=null,enhanceQueued=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const bioName=()=>isIOS()?'Face ID / Touch ID':'Biometrie / apparaatbeveiliging';
const accessKey=id=>'mms_access3_'+id;
const readAccess=id=>{try{return JSON.parse(localStorage.getItem(accessKey(id))||'null')}catch{return null}};
const writeAccess=(id,v)=>localStorage.setItem(accessKey(id),JSON.stringify({v:3,id,...v}));

function db(){if(dbPromise)return dbPromise;dbPromise=new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbPromise}
async function all(store){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function put(store,val){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).put(val);r.onsuccess=()=>res(val);r.onerror=()=>rej(r.error)})}
async function api(path,opt={}){const r=await fetch(API_BASE+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b}

async function createIdentity(label){
  label=(label||'').trim();if(label.length<2)throw new Error('Naam is te kort.');
  const secret=B64.url(rand(32)),id=newId(),keys=await genKeys(),mailboxAuth=B64.url(rand(32));
  const authHash=B64.url(await sha256(mailboxAuth)),bundleSig=await signBundle(keys,id);
  await api('/api/register',{method:'POST',body:JSON.stringify({id,authHash,signAlg:keys.signAlg,agreeAlg:keys.agreeAlg,signPub:keys.signPub,agreePub:keys.agreePub,bundleSig})});
  const master=rand(32),salt=rand(32),kek=await deriveKEK(secret,salt),wrapped=await aesEnc(kek,master,'MMS-V4-MASTER:'+id);
  const vault={v:4,phone:null,mailboxAuth,privateKeys:{signPriv:keys.signPriv,agreePriv:keys.agreePriv},public:{id,signAlg:keys.signAlg,agreeAlg:keys.agreeAlg,signPub:keys.signPub,agreePub:keys.agreePub,bundleSig},contacts:{},chats:{},ratchets:{},seen:{},security:{createdAt:Date.now(),lastPasswordChange:null}};
  const box=await aesEnc(master,JSON.stringify(vault),'MMS-V4-VAULT:'+id);
  await put('accounts',{id,label,createdAt:Date.now(),signFingerprint:await fingerprintJwk(keys.signPub)});
  await put('vaults',{id,wrap:{salt:B64.enc(salt),iters:ITERS,wrapped},box,updatedAt:Date.now()});
  writeAccess(id,{mode:'none',secret});sessionStorage.setItem('mms_access3_autopen',id);location.reload();
}

async function waitFor(fn,ms=15000){const end=Date.now()+ms;while(Date.now()<end){const v=fn();if(v)return v;await sleep(40)}return null}
async function openCore(a,secret,original){activeId=a.id;pendingSecret=secret;original();const input=await waitFor(()=>document.querySelector('#gate input[type="password"]'));if(!input)throw new Error('MMS-ontgrendelscherm ontbreekt.');input.value=secret;const b=[...document.querySelectorAll('#gate button')].find(x=>(x.textContent||'').trim()==='Ontgrendel');if(!b)throw new Error('MMS-ontgrendelknop ontbreekt.');b.click();const ok=await waitFor(()=>document.getElementById('gate')?.classList.contains('hidden'),20000);if(!ok)throw new Error('MMS kon deze identiteit niet openen.');sessionSecret=secret;pendingSecret=null}
function captureLegacyUnlock(id){setTimeout(async()=>{const input=await waitFor(()=>document.querySelector('#gate input[type="password"]'),4000);const b=[...document.querySelectorAll('#gate button')].find(x=>(x.textContent||'').trim()==='Ontgrendel');if(!input||!b)return;const remember=()=>{activeId=id;pendingSecret=input.value;setTimeout(()=>{if(document.getElementById('gate')?.classList.contains('hidden'))sessionSecret=pendingSecret},1500)};b.addEventListener('click',remember,{capture:true,once:true});input.addEventListener('keydown',e=>{if(e.key==='Enter')remember()},{capture:true,once:true})},0)}

function validUserLock(s){if(/^\d+$/.test(s))return s.length>=6&&s.length<=12;return s.length>=8}
async function makeSecretWrap(id,unlockSecret,userLock){if(!validUserLock(userLock))throw new Error('Gebruik minimaal 6 cijfers voor een PIN of minimaal 8 tekens voor een wachtwoord.');const salt=rand(32),key=await deriveKEK(userLock,salt);return{mode:'secret',salt:B64.enc(salt),iters:ITERS,wrapped:await aesEnc(key,unlockSecret,'MMS-ACCESS3-SECRET:'+id)}}
async function secretFromWrap(id,rec,userLock){const key=await deriveKEK(userLock,B64.dec(rec.salt),rec.iters||ITERS);return TD.decode(await aesDec(key,rec.wrapped,'MMS-ACCESS3-SECRET:'+id))}
function webauthnOK(){return location.protocol==='https:'&&!!window.PublicKeyCredential&&!!navigator.credentials?.create&&!!navigator.credentials?.get}
async function prfKey(id,out){return sha256(concat(TE.encode('MMS-ACCESS3-PRF|'+id+'|'),new Uint8Array(out)))}
async function createBio(id,label,unlockSecret,fallback=null){
  if(!webauthnOK())throw new Error(bioName()+' wordt door deze browser niet ondersteund.');const salt=rand(32);
  const cred=await navigator.credentials.create({publicKey:{challenge:rand(32),rp:{name:'MMS',id:location.hostname},user:{id:rand(24),name:'mms-'+id.slice(0,12),displayName:label||'MMS'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-8}],authenticatorSelection:{authenticatorAttachment:'platform',residentKey:'preferred',userVerification:'required'},timeout:60000,attestation:'none',extensions:{prf:{eval:{first:salt}}}}});
  if(!cred)throw new Error('Biometrische registratie is geannuleerd.');const credentialId=B64.url(new Uint8Array(cred.rawId));let out=cred.getClientExtensionResults?.()?.prf?.results?.first;
  if(!out){const assertion=await navigator.credentials.get({publicKey:{challenge:rand(32),rpId:location.hostname,allowCredentials:[{type:'public-key',id:B64.unurl(credentialId)}],userVerification:'required',timeout:60000,extensions:{prf:{eval:{first:salt}}}}});out=assertion?.getClientExtensionResults?.()?.prf?.results?.first}
  if(!out)throw new Error('Deze browser geeft geen biometrische PRF-sleutel vrij.');return{mode:'biometric',credentialId,salt:B64.enc(salt),wrapped:await aesEnc(await prfKey(id,out),unlockSecret,'MMS-ACCESS3-BIO:'+id),fallback};
}
async function bioSecret(id,rec){const assertion=await navigator.credentials.get({publicKey:{challenge:rand(32),rpId:location.hostname,allowCredentials:[{type:'public-key',id:B64.unurl(rec.credentialId)}],userVerification:'required',timeout:60000,extensions:{prf:{eval:{first:B64.dec(rec.salt)}}}}});const out=assertion?.getClientExtensionResults?.()?.prf?.results?.first;if(!out)throw new Error(bioName()+' kon de lokale MMS-sleutel niet vrijgeven.');return TD.decode(await aesDec(await prfKey(id,out),rec.wrapped,'MMS-ACCESS3-BIO:'+id))}

function modal(title,copy){const m=document.getElementById('modal');m.innerHTML='<h2>'+title+'</h2><p>'+copy+'</p>';m.classList.remove('hidden');return m}
function closeBtn(m,label='Annuleren'){const b=document.createElement('button');b.className='btn';b.style.cssText='width:100%;margin-top:8px';b.textContent=label;b.onclick=()=>m.classList.add('hidden');return b}
async function showUserLock(a,rec,original){const m=modal('Ontgrendel MMS','Voer je PIN of wachtwoord in. Dit blijft alleen op je apparaat.');const w=document.createElement('div');w.className='field';w.innerHTML='<label>PIN of wachtwoord</label><input type="password" autocomplete="current-password">';const e=document.createElement('div');e.className='error';const go=document.createElement('button');go.className='btn primary';go.style.width='100%';go.textContent='Ontgrendel';go.onclick=async()=>{go.disabled=true;e.textContent='';try{const secret=await secretFromWrap(a.id,rec,w.querySelector('input').value);m.classList.add('hidden');await openCore(a,secret,original)}catch(err){e.textContent='PIN of wachtwoord klopt niet.';go.disabled=false}};w.querySelector('input').onkeydown=ev=>{if(ev.key==='Enter')go.click()};m.append(w,e,go,closeBtn(m));setTimeout(()=>w.querySelector('input').focus(),0)}

async function enhanceAccounts(){
  const list=document.querySelector('#gate .accounts');if(!list)return;const as=await all('accounts');
  for(const row of list.querySelectorAll('.account')){if(row.dataset.access3==='1')continue;row.dataset.access3='1';const sm=row.querySelector('small'),primary=row.querySelector('button');if(!sm||!primary)continue;const prefix=((sm.textContent||'').match(/MMS ID\s+([^…]+)/)||[])[1]||'',a=as.find(x=>x.id.startsWith(prefix));if(!a)continue;const original=primary.onclick,rec=readAccess(a.id);
    if(!rec){primary.onclick=()=>{activeId=a.id;original();captureLegacyUnlock(a.id)};continue}
    const actions=document.createElement('div');actions.style.cssText='display:flex;gap:6px;flex-wrap:wrap';primary.remove();actions.append(primary);row.append(actions);
    if(rec.mode==='none'){primary.textContent='Open';primary.onclick=async()=>{primary.disabled=true;try{await openCore(a,rec.secret,original)}catch(e){alert(e.message||String(e))}finally{primary.disabled=false}}}
    else if(rec.mode==='secret'){primary.textContent='Ontgrendel';primary.onclick=()=>showUserLock(a,rec,original)}
    else if(rec.mode==='biometric'){primary.textContent=bioName();primary.onclick=async()=>{primary.disabled=true;try{await openCore(a,await bioSecret(a.id,rec),original)}catch(e){if(rec.fallback)showUserLock(a,rec.fallback,original);else alert((e.message||String(e))+' Probeer opnieuw; je telefoon kan ook de apparaatcode aanbieden.')}finally{primary.disabled=false}};if(rec.fallback){const fb=document.createElement('button');fb.className='btn';fb.textContent='PIN / wachtwoord';fb.onclick=()=>showUserLock(a,rec.fallback,original);actions.append(fb)}}
    const auto=sessionStorage.getItem('mms_access3_autopen');if(auto===a.id){sessionStorage.removeItem('mms_access3_autopen');setTimeout(()=>primary.click(),60)}
  }
}

function enhanceCreate(){const c=document.querySelector('#gate .card');if(!c||c.dataset.access3Create==='1'||(c.querySelector('h2')?.textContent||'').trim()!=='Nieuwe MMS-identiteit')return;c.dataset.access3Create='1';c.innerHTML='<h2>Nieuwe MMS-identiteit</h2><div class="notice good"><strong>Geen wachtwoord nodig.</strong><br>Je identiteit wordt direct lokaal beveiligd aangemaakt. Een PIN, wachtwoord of '+bioName()+' kun je later optioneel instellen onder <b>Beveiliging</b>.</div>';const w=document.createElement('div');w.className='field';w.innerHTML='<label>Naam op dit apparaat</label><input type="text" autocomplete="name" placeholder="Querijn">';const e=document.createElement('div');e.className='error',row=document.createElement('div');row.className='row';const back=document.createElement('button');back.className='btn';back.textContent='Terug';back.onclick=()=>location.reload();const go=document.createElement('button');go.className='btn primary';go.textContent='Maak identiteit';go.onclick=async()=>{go.disabled=true;back.disabled=true;e.style.color='var(--muted)';e.textContent='Sleutels en lokale vault worden aangemaakt…';try{await createIdentity(w.querySelector('input').value)}catch(err){e.style.color='';e.textContent=err.message||String(err);go.disabled=false;back.disabled=false}};row.append(back,go);c.append(w,e,row);setTimeout(()=>w.querySelector('input').focus(),0)}

async function currentAccount(){const as=await all('accounts');if(activeId){const a=as.find(x=>x.id===activeId);if(a)return a}const info=document.getElementById('meInfo')?.textContent||'',m=info.match(/MMS\s+([A-Za-z0-9_-]{8})/);if(m){const a=as.find(x=>x.id.startsWith(m[1]));if(a){activeId=a.id;return a}}const label=document.getElementById('meName')?.textContent||'',same=as.filter(x=>x.label===label);return same.length===1?same[0]:null}
async function ensureSessionSecret(a){if(sessionSecret)return sessionSecret;const rec=readAccess(a.id);if(rec?.mode==='none')return rec.secret;throw new Error('Vergrendel MMS en open deze identiteit één keer opnieuw voordat je de beveiliging wijzigt.')}
async function configureLock(a){const secret=await ensureSessionSecret(a),rec=readAccess(a.id);const m=modal('PIN of wachtwoord instellen','Dit is optioneel. Gebruik een numerieke PIN of een normaal wachtwoord. '+(rec?.mode==='biometric'?'Je '+bioName()+' blijft actief en dit wordt de fallback.':''));const w1=document.createElement('div');w1.className='field';w1.innerHTML='<label>Nieuwe PIN of wachtwoord</label><input type="password" autocomplete="new-password" placeholder="6+ cijfers of 8+ tekens">';const w2=document.createElement('div');w2.className='field';w2.innerHTML='<label>Herhaal</label><input type="password" autocomplete="new-password">';const e=document.createElement('div');e.className='error',go=document.createElement('button');go.className='btn primary';go.style.width='100%';go.textContent='Opslaan';go.onclick=async()=>{e.textContent='';try{const a1=w1.querySelector('input').value,a2=w2.querySelector('input').value;if(a1!==a2)throw new Error('De invoer is niet gelijk.');const sw=await makeSecretWrap(a.id,secret,a1);if(rec?.mode==='biometric'){rec.fallback=sw;writeAccess(a.id,rec)}else writeAccess(a.id,sw);m.classList.add('hidden')}catch(err){e.textContent=err.message||String(err)}};m.append(w1,w2,e,go,closeBtn(m));setTimeout(()=>w1.querySelector('input').focus(),0)}
async function configureBio(a){const secret=await ensureSessionSecret(a),rec=readAccess(a.id);const m=modal(bioName()+' inschakelen','Biometrie beschermt het openen van je lokale MMS-sessie. Je gezicht of vingerafdruk komt nooit bij MMS of de relay. Op iPhone kan het systeem ook de apparaatcode als fallback aanbieden.');const e=document.createElement('div');e.className='error',go=document.createElement('button');go.className='btn primary';go.style.width='100%';go.textContent='Activeer '+bioName();go.onclick=async()=>{go.disabled=true;e.textContent='';try{const fallback=rec?.mode==='secret'?rec:(rec?.mode==='biometric'?rec.fallback:null);writeAccess(a.id,await createBio(a.id,a.label,secret,fallback));m.classList.add('hidden')}catch(err){e.textContent=err.message||String(err);go.disabled=false}};m.append(e,go,closeBtn(m))}
async function disableLock(a){const secret=await ensureSessionSecret(a);writeAccess(a.id,{mode:'none',secret});document.getElementById('modal').classList.add('hidden')}
async function disableBioKeepFallback(a,rec){const secret=await ensureSessionSecret(a);writeAccess(a.id,rec?.fallback||{mode:'none',secret});document.getElementById('modal').classList.add('hidden')}

async function enhanceSecurity(){const m=document.getElementById('modal');if(!m||m.classList.contains('hidden')||m.querySelector('[data-access3-security]')||(m.querySelector('h2')?.textContent||'').trim()!=='MMS Security State')return;const a=await currentAccount();if(!a)return;const rec=readAccess(a.id),sec=document.createElement('div');sec.dataset.access3Security='1';sec.style.cssText='border-top:1px solid var(--line);margin-top:14px;padding-top:14px';const mode=rec?.mode==='biometric'?bioName()+(rec.fallback?' + PIN/wachtwoord':''):rec?.mode==='secret'?'PIN / wachtwoord':'Geen extra sessievergrendeling';sec.innerHTML='<strong>Sessie openen</strong><div style="margin:7px 0;font-size:11px;color:var(--accent)">'+mode+'</div><small style="display:block;color:var(--muted);margin-bottom:10px">Beveiliging is optioneel. Je E2EE-berichten blijven versleuteld ongeacht deze keuze.</small>';const lock=document.createElement('button');lock.className='btn';lock.style.width='100%';lock.textContent='PIN / wachtwoord instellen';lock.onclick=()=>configureLock(a).catch(e=>alert(e.message||String(e)));sec.append(lock);if(rec?.mode!=='biometric'){const bio=document.createElement('button');bio.className='btn primary';bio.style.cssText='width:100%;margin-top:8px';bio.textContent=bioName()+' inschakelen';bio.onclick=()=>configureBio(a).catch(e=>alert(e.message||String(e)));sec.append(bio)}if(rec?.mode==='biometric'){const off=document.createElement('button');off.className='btn';off.style.cssText='width:100%;margin-top:8px';off.textContent=bioName()+' uitschakelen';off.onclick=()=>disableBioKeepFallback(a,rec).catch(e=>alert(e.message||String(e)));sec.append(off)}if(rec?.mode!=='none'){const none=document.createElement('button');none.className='btn';none.style.cssText='width:100%;margin-top:8px';none.textContent='Geen extra sessievergrendeling';none.onclick=()=>disableLock(a).catch(e=>alert(e.message||String(e)));sec.append(none)}m.insertBefore(sec,m.lastElementChild||null)}

async function inviteCode(){const b=document.getElementById('inviteBtn');if(!b||b.disabled)throw new Error('Ontgrendel eerst MMS.');b.click();const box=await waitFor(()=>document.querySelector('#modal .codebox'));if(!box)throw new Error('Invite kon niet worden gemaakt.');const code=box.textContent||'';document.getElementById('modal').classList.add('hidden');return code}
async function inviteContact(){const code=await inviteCode(),text='Ik nodig je uit voor MMS — Mattheüs Messaging Service. Open https://opulenzo-create.github.io/ en voeg mij toe met deze MMS invite-code:\n\n'+code;const m=modal('Contact uitnodigen','Je privésleutel en berichten worden niet gedeeld.');if(navigator.contacts?.select){const p=document.createElement('button');p.className='btn primary';p.style.width='100%';p.textContent='Kies uit contacten';p.onclick=async()=>{try{const c=await navigator.contacts.select(['name','tel'],{multiple:false}),tel=c?.[0]?.tel?.[0];if(tel)location.href='sms:'+tel+'?body='+encodeURIComponent(text)}catch(e){if(e.name!=='AbortError')alert(e.message||String(e))}};m.append(p)}const share=document.createElement('button');share.className='btn primary';share.style.cssText='width:100%;margin-top:8px';share.textContent=isIOS()?'Kies contact via Delen':'Delen';share.onclick=async()=>{try{if(navigator.share)await navigator.share({title:'MMS uitnodiging',text});else{await navigator.clipboard.writeText(text);alert('Uitnodiging gekopieerd.')}}catch(e){if(e.name!=='AbortError')alert(e.message||String(e))}};const copy=document.createElement('button');copy.className='btn';copy.style.cssText='width:100%;margin-top:8px';copy.textContent='Kopieer uitnodiging';copy.onclick=async()=>{await navigator.clipboard.writeText(text);copy.textContent='Gekopieerd'};m.append(share,copy,closeBtn(m,'Sluiten'))}
function enhanceInvite(){const add=document.querySelector('.side .add');if(add&&!document.getElementById('inviteContact3')){const b=document.createElement('button');b.id='inviteContact3';b.className='btn';b.textContent='Nodig contact uit';b.onclick=()=>inviteContact().catch(e=>alert(e.message||String(e)));add.insertBefore(b,document.getElementById('contactError')||null)}const b=document.getElementById('inviteContact3');if(b)b.disabled=document.getElementById('inviteCodeBtn')?.disabled??true}

async function enhance(){try{await enhanceAccounts();enhanceCreate();await enhanceSecurity();enhanceInvite()}catch(e){console.warn('MMS Access 0.10:',e)}}
function queueEnhance(){if(enhanceQueued)return;enhanceQueued=true;queueMicrotask(()=>{enhanceQueued=false;enhance()})}
const gate=document.getElementById('gate'),modalEl=document.getElementById('modal');new MutationObserver(queueEnhance).observe(gate,{childList:true});new MutationObserver(queueEnhance).observe(modalEl,{childList:true});addEventListener('pageshow',queueEnhance);setTimeout(queueEnhance,0);
