'use strict';

(()=>{
const CORE='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms';
const CALL='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms-call';
const BUILD='0.13.0-security2-call-sas';
let selfId='',mailboxToken='',incomingPoll=null,signalPoll=null,active=null,lastIncoming='';
const upstreamFetch=window.fetch.bind(window);

function reqUrl(input){return typeof input==='string'?input:(input?.url||'')}
function headersOf(input,init){const h=new Headers(input instanceof Request?input.headers:undefined);new Headers(init?.headers||{}).forEach((v,k)=>h.set(k,v));return h}
function parseBody(init){try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}}
window.fetch=async function(input,init={}){
  const url=reqUrl(input);try{const h=headersOf(input,init),a=h.get('authorization')||'';if(url.startsWith(CORE)&&a.startsWith('Bearer ')){mailboxToken=a.slice(7);const m=url.match(/\/api\/inbox\/([^/?#]+)/);if(m)selfId=decodeURIComponent(m[1]);const b=parseBody(init);if(!selfId&&b)selfId=b.requesterId||b.ownerId||b.from||b.id||'';ready()}}catch{}
  return upstreamFetch(input,init);
};

function auth(){return{'Authorization':'Bearer '+mailboxToken,'Content-Type':'application/json'}}
async function req(base,path,opt={}){const r=await upstreamFetch(base+path,{...opt,headers:{...(opt.headers||{}),...(mailboxToken?auth():{'Content-Type':'application/json'})},cache:'no-store'});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b}
function e(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x}
function short(id){return id?('MMS '+id.slice(0,8)+'…'):'MMS-contact'}
function trusted(id){return !!window.MMS_SECURITY2?.isTrusted?.(id)}
function human(err){const m=err?.message||String(err);if(err?.name==='NotAllowedError')return'Microfoontoegang is geweigerd.';if(m.includes('SECURITY_'))return'Beveiliging blokkeerde deze identiteit. Controleer Security.';if(m==='untrusted_peer')return'Dit contact is nog niet lokaal/keylog-gepind. Open of voeg het contact eerst toe in MMS.';if(m==='call_rate_limited')return'Te veel belpogingen. Probeer later opnieuw.';if(m==='recipient_not_found'||m==='not_found')return'Dit MMS-contact is niet bereikbaar.';return m}
function supports(){return !!(window.RTCPeerConnection&&navigator.mediaDevices?.getUserMedia)}
function layer(){let l=document.getElementById('mmsCallLayer');if(!l){l=e('div','mmsCallLayer');l.id='mmsCallLayer';document.body.append(l)}return l}
function hide(){const l=layer();l.classList.add('hidden');l.replaceChildren()}
function show(){layer().classList.remove('hidden')}
function style(){if(document.getElementById('mmsCallStyle'))return;const s=document.createElement('style');s.id='mmsCallStyle';s.textContent=`.mmsCallLayer{position:fixed;inset:0;z-index:140;background:rgba(2,8,6,.9);backdrop-filter:blur(22px);display:grid;place-items:center;padding:16px}.mmsCallLayer.hidden{display:none}.mmsCallCard{width:min(430px,100%);background:#0b1813;border:1px solid #315747;border-radius:28px;padding:26px;text-align:center;box-shadow:0 30px 90px #0009}.mmsCallAvatar{width:88px;height:88px;border-radius:30px;margin:0 auto 16px;background:#62e6ae;color:#042117;display:grid;place-items:center;font-size:34px;font-weight:900}.mmsCallName{font-size:23px;font-weight:900}.mmsCallStatus{color:#9ab8ad;margin:8px 0 16px}.mmsCallCode{border:1px solid #315747;background:#07110e;border-radius:14px;padding:12px;margin:12px 0;font:800 18px/1.5 ui-monospace,monospace;letter-spacing:.04em}.mmsCallHint{font-size:11px;color:#8aa79c;line-height:1.5}.mmsCallActions{display:flex;justify-content:center;gap:18px;margin-top:20px}.mmsCallRound{width:62px;height:62px;border-radius:50%;border:1px solid #315747;background:#102019;color:#eef9f5;font-size:23px;cursor:pointer}.mmsCallRound.primary{background:#62e6ae;color:#042117;border:0}.mmsCallRound.danger{background:#d95050;color:white;border:0}.mmsCallField{text-align:left;margin:16px 0}.mmsCallField input{width:100%;box-sizing:border-box;border:1px solid #29463b;background:#07110e;color:#eef9f5;border-radius:12px;padding:12px}.mmsCallRow{display:flex;gap:8px}.mmsCallRow button{flex:1}.mmsCallError{color:#ffaaaa;min-height:18px;font-size:11px}.mmsCallLabel{font-size:10px;color:#8aa79c;margin-top:5px}`;document.head.append(s)}
function buttonWrap(btn,label){const w=e('div');w.append(btn,e('div','mmsCallLabel',label));return w}
function installButtons(){style();let b=document.getElementById('mmsCallBtn');if(!b){b=e('button','btn','☎ Bellen');b.id='mmsCallBtn';b.onclick=dialer;document.querySelector('.actions')?.insertBefore(b,document.getElementById('guestBtn')||null)}let m=document.getElementById('mmsMobileCallBtn');if(!m){m=e('button','iconBtn','☎');m.id='mmsMobileCallBtn';m.setAttribute('aria-label','Bellen');m.onclick=dialer;document.querySelector('.mobileTopActions')?.insertBefore(m,document.getElementById('mobileLockBtn')||null)}b.disabled=!mailboxToken;m.disabled=!mailboxToken}
function ready(){installButtons();if(!incomingPoll)incomingPoll=setInterval(checkIncoming,1800);checkIncoming()}
async function mic(){return navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})}
function waitIce(pc,ms=9000){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(res=>{let done=false;const f=()=>{if(!done&&pc.iceGatheringState==='complete'){done=true;pc.removeEventListener('icegatheringstatechange',f);res()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(()=>{if(!done){done=true;pc.removeEventListener('icegatheringstatechange',f);res()}},ms)})}
function peer(stream){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}],iceCandidatePoolSize:2});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=ev=>{let a=document.getElementById('mmsRemoteAudio');if(!a){a=document.createElement('audio');a.id='mmsRemoteAudio';a.autoplay=true;a.playsInline=true;document.body.append(a)}a.srcObject=ev.streams[0];a.play?.().catch(()=>{})};pc.onconnectionstatechange=()=>{if(!active||active.pc!==pc)return;if(pc.connectionState==='connected')setStatus('Verbonden — vergelijk de beveiligingscode');if(['failed','disconnected'].includes(pc.connectionState))setStatus('Verbinding onderbroken')};return pc}
function fp(desc){const m=desc?.sdp?.match(/a=fingerprint:sha-256\s+([A-F0-9:]+)/i);return m?m[1].toUpperCase():''}
async function safetyCode(pc,callId){const a=fp(pc.localDescription),b=fp(pc.remoteDescription);if(!a||!b)return'';const src=['MMS-CALL-SAS-V1',callId,...[a,b].sort()].join('|');const d=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(src)));return [...d.slice(0,6)].map(x=>x.toString().padStart(3,'0')).join(' ')}
async function refreshCode(){if(!active)return;const code=await safetyCode(active.pc,active.id);const c=document.getElementById('mmsCallCode');if(c)c.textContent=code||'code nog niet beschikbaar'}
function setStatus(s){const n=document.getElementById('mmsCallStatus');if(n)n.textContent=s}
function callScreen(peerId,status){const l=layer();l.replaceChildren();const c=e('div','mmsCallCard');c.append(e('div','mmsCallAvatar','M'),e('div','mmsCallName',short(peerId)));const st=e('div','mmsCallStatus',status);st.id='mmsCallStatus';c.append(st);const code=e('div','mmsCallCode','code wordt opgebouwd…');code.id='mmsCallCode';c.append(code,e('div','mmsCallHint','Vergelijk deze code hardop met de andere persoon. Alleen wanneer beide codes exact gelijk zijn, is een signaling-MITM gedetecteerd als afwezig voor deze oproep.'));const acts=e('div','mmsCallActions'),mute=e('button','mmsCallRound','🎙'),hang=e('button','mmsCallRound danger','✕');mute.onclick=()=>{if(!active)return;active.muted=!active.muted;active.stream.getAudioTracks().forEach(t=>t.enabled=!active.muted);mute.textContent=active.muted?'🔇':'🎙'};hang.onclick=()=>endCall(true);acts.append(buttonWrap(mute,'Mute'),buttonWrap(hang,'Ophangen'));c.append(acts);l.append(c);show()}
function dialer(){if(!mailboxToken||!selfId)return alert('Ontgrendel eerst je MMS-identiteit.');const l=layer();l.replaceChildren();const c=e('div','mmsCallCard');c.append(e('div','mmsCallAvatar','☎'),e('div','mmsCallName','Beveiligd MMS-bellen'),e('div','mmsCallStatus','Bel een bestaand/gepind MMS-contact.'));const f=e('div','mmsCallField'),i=document.createElement('input');i.placeholder='+316… of MMS-ID';i.autocomplete='off';f.append(i);const er=e('div','mmsCallError'),row=e('div','mmsCallRow'),cancel=e('button','btn','Annuleren'),go=e('button','btn primary','Bel');cancel.onclick=hide;go.onclick=async()=>{go.disabled=true;er.textContent='';try{let id=i.value.trim();if(id.startsWith('+')){const r=await req(CORE,'/api/discover',{method:'POST',body:JSON.stringify({requesterId:selfId,phone:id})});id=r.profile?.id||''}if(!/^[A-Za-z0-9_-]{16,80}$/.test(id)||id===selfId)throw new Error('Geen geldig MMS-contact.');if(!trusted(id))throw new Error('untrusted_peer');await outgoing(id)}catch(x){er.textContent=human(x);go.disabled=false}};i.onkeydown=x=>{if(x.key==='Enter')go.click()};row.append(cancel,go);c.append(f,er,row,e('div','mmsCallHint','Audio is via WebRTC versleuteld. De zichtbare safety-code authenticeert de DTLS-fingerprints tussen beide toestellen.'));l.append(c);show();setTimeout(()=>i.focus(),0)}
async function outgoing(peerId){if(!supports())throw new Error('Bellen wordt niet ondersteund op dit apparaat.');if(active)throw new Error('Er is al een oproep actief.');let stream,pc;try{stream=await mic();pc=peer(stream);const id=crypto.randomUUID().replace(/-/g,'')+Math.random().toString(36).slice(2,8);active={id,peer:peerId,stream,pc,direction:'out',muted:false};callScreen(peerId,'Bellen…');const offer=await pc.createOffer({offerToReceiveAudio:true});await pc.setLocalDescription(offer);await waitIce(pc);await req(CALL,'/start',{method:'POST',body:JSON.stringify({callerId:selfId,calleeId:peerId,callId:id,offer:pc.localDescription})});startSignals()}catch(x){try{stream?.getTracks().forEach(t=>t.stop());pc?.close()}catch{}active=null;hide();throw x}}
async function checkIncoming(){if(!mailboxToken||!selfId||active||document.hidden)return;try{const r=await req(CALL,'/incoming/'+encodeURIComponent(selfId));const c=r.calls?.[0];if(!c||c.id===lastIncoming)return;lastIncoming=c.id;if(!trusted(c.caller_id)){await req(CALL,'/decline/'+encodeURIComponent(c.id),{method:'POST',body:JSON.stringify({calleeId:selfId})});console.warn('MMS Security 2 blocked unknown caller',c.caller_id);return}incoming(c)}catch{}}
function incoming(call){const l=layer();l.replaceChildren();const c=e('div','mmsCallCard');c.append(e('div','mmsCallAvatar','☎'),e('div','mmsCallName',short(call.caller_id)),e('div','mmsCallStatus','Inkomende gepinde MMS-oproep'));const a=e('div','mmsCallActions'),no=e('button','mmsCallRound danger','✕'),yes=e('button','mmsCallRound primary','☎');no.onclick=()=>decline(call);yes.onclick=()=>answer(call);a.append(buttonWrap(no,'Weiger'),buttonWrap(yes,'Neem op'));c.append(a);l.append(c);show();navigator.vibrate?.([160,80,160])}
async function answer(call){let stream,pc;try{const sig=await req(CALL,'/signals/'+encodeURIComponent(call.id)+'?id='+encodeURIComponent(selfId)),offer=sig.signals?.find(x=>x.kind==='offer')?.payload;if(!offer)throw new Error('Oproepdata ontbreekt.');stream=await mic();pc=peer(stream);active={id:call.id,peer:call.caller_id,stream,pc,direction:'in',muted:false};callScreen(call.caller_id,'Verbinden…');await pc.setRemoteDescription(offer);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);await refreshCode();await req(CALL,'/answer/'+encodeURIComponent(call.id),{method:'POST',body:JSON.stringify({calleeId:selfId,answer:pc.localDescription})});startSignals()}catch(x){try{stream?.getTracks().forEach(t=>t.stop());pc?.close()}catch{}active=null;hide();alert(human(x));await decline(call,true)}}
async function decline(call,silent=false){try{await req(CALL,'/decline/'+encodeURIComponent(call.id),{method:'POST',body:JSON.stringify({calleeId:selfId})})}catch{}hide();if(!silent)navigator.vibrate?.(25)}
function startSignals(){stopSignals();signalPoll=setInterval(pollSignals,900);pollSignals()}
function stopSignals(){if(signalPoll){clearInterval(signalPoll);signalPoll=null}}
async function pollSignals(){if(!active)return;try{const r=await req(CALL,'/signals/'+encodeURIComponent(active.id)+'?id='+encodeURIComponent(selfId));for(const s of r.signals||[]){if(s.kind==='answer'&&active.direction==='out'&&s.payload&&!active.pc.remoteDescription){await active.pc.setRemoteDescription(s.payload);await refreshCode();setStatus('Verbinden…')}else if(s.kind==='decline'){setStatus('Oproep geweigerd');setTimeout(()=>endCall(false),700)}else if(s.kind==='hangup'){setStatus('Gesprek beëindigd');setTimeout(()=>endCall(false),350)}}if(r.state==='missed'){setStatus('Geen antwoord');setTimeout(()=>endCall(false),700)}}catch(x){console.warn('MMS call signaling:',x?.message||x)}}
async function endCall(notify){const a=active;if(!a){hide();return}active=null;stopSignals();try{a.stream?.getTracks().forEach(t=>t.stop());a.pc?.close()}catch{}const ra=document.getElementById('mmsRemoteAudio');if(ra){ra.srcObject=null;ra.remove()}hide();if(notify&&mailboxToken)try{await req(CALL,'/hangup/'+encodeURIComponent(a.id),{method:'POST',body:JSON.stringify({id:selfId})})}catch{}}
window.addEventListener('pagehide',()=>{if(active)endCall(true)});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{style();installButtons()});else{style();installButtons()}
console.info('MMS Calls',BUILD);
})();
