'use strict';

const CORE='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms';
const CALL='https://qpgiqpnkyxbajjyhrsyr.supabase.co/functions/v1/mms-call';
let selfId='',token='',incomingTimer=null,signalTimer=null,active=null,keepTimer=null,lastIncoming='';
const upstream=window.fetch.bind(window);

window.fetch=async function(input,init={}){
  const url=typeof input==='string'?input:(input?.url||'');
  try{
    const h=new Headers(input instanceof Request?input.headers:undefined);new Headers(init.headers||{}).forEach((v,k)=>h.set(k,v));
    const a=h.get('authorization')||'',m=url.match(/\/api\/inbox\/([^/?#]+)/);
    if(url.startsWith(CORE)&&a.startsWith('Bearer ')&&m){selfId=decodeURIComponent(m[1]);token=a.slice(7);ready()}
  }catch{}
  return upstream(input,init);
};

const E=(t,c='',x='')=>{const n=document.createElement(t);if(c)n.className=c;if(x)n.textContent=x;return n};
const short=id=>id?'MMS '+id.slice(0,8)+'…':'MMS-contact';
const auth=()=>({'Authorization':'Bearer '+token,'Content-Type':'application/json'});
async function api(base,path,opt={}){const r=await upstream(base+path,{...opt,headers:{...(opt.headers||{}),...auth()}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||'HTTP '+r.status);return b}
function human(e){const m=e?.message||String(e);if(e?.name==='NotAllowedError'||m==='NotAllowedError')return'Microfoontoegang is geweigerd. Geef MMS toegang tot je microfoon.';if(m==='call_rate_limited')return'Te veel belpogingen. Probeer later opnieuw.';if(m==='recipient_not_found'||m==='not_found')return'Dit MMS-contact is niet bereikbaar.';if(m==='call_expired')return'De oproep is verlopen.';return m}
function supported(){return !!(window.RTCPeerConnection&&navigator.mediaDevices?.getUserMedia)}
async function mic(){return navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})}
function randId(){const u=new Uint8Array(24);crypto.getRandomValues(u);return Array.from(u,b=>b.toString(16).padStart(2,'0')).join('')}
function waitIce(pc,ms=9000){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(res=>{let done=false;const f=()=>{if(!done&&pc.iceGatheringState==='complete'){done=true;pc.removeEventListener('icegatheringstatechange',f);res()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(()=>{if(!done){done=true;pc.removeEventListener('icegatheringstatechange',f);res()}},ms)})}

function style(){if(document.getElementById('mmsCallStyle'))return;const s=E('style');s.id='mmsCallStyle';s.textContent=`#mmsCallLayer{position:fixed;inset:0;z-index:140;background:rgba(2,8,6,.9);backdrop-filter:blur(22px);display:grid;place-items:center;padding:16px}#mmsCallLayer.hidden{display:none!important}.mCall{width:min(430px,100%);background:linear-gradient(180deg,#10221b,#07120e);border:1px solid #315747;border-radius:28px;padding:26px;box-shadow:0 30px 100px #0009;text-align:center}.mCallAv{width:88px;height:88px;margin:0 auto 16px;border-radius:30px;background:linear-gradient(145deg,#62e6ae,#18835c);display:grid;place-items:center;color:#042117;font-size:34px;font-weight:1000}.mCallName{font-size:23px;font-weight:900}.mCallStatus{color:#86a399;margin:8px 0 22px;min-height:22px}.mCallActions{display:flex;justify-content:center;gap:16px;flex-wrap:wrap}.mCallRound{width:62px;height:62px;border-radius:50%;border:1px solid #315747;background:#102019;color:#eef9f5;font-size:24px;display:grid;place-items:center;cursor:pointer}.mCallRound.ok{background:#62e6ae;color:#042117;border:0}.mCallRound.no{background:#d95050;color:#fff;border:0}.mCallLabel{font-size:10px;color:#86a399;margin-top:6px}.mCallField{text-align:left;margin:14px 0}.mCallField label{display:block;font-size:11px;color:#b9cec6;margin-bottom:6px}.mCallField input{width:100%;border:1px solid #203b31;background:#08140f;color:#eef9f5;border-radius:12px;padding:12px}.mCallErr{color:#ffabab;font-size:11px;min-height:18px;margin:5px 0}.mCallRow{display:flex;gap:8px}.mCallRow>*{flex:1}.mCallTiny{font-size:10px;color:#86a399;line-height:1.45;margin-top:13px}@media(max-width:820px){.mCall{padding:23px 18px}.mCallName{font-size:21px}}`;document.head.append(s)}
function layer(){let l=document.getElementById('mmsCallLayer');if(!l){l=E('div','hidden');l.id='mmsCallLayer';document.body.append(l)}return l}
function closeLayer(){const l=layer();l.classList.add('hidden');l.innerHTML=''}
function openLayer(){layer().classList.remove('hidden')}
function setStatus(t){const e=document.getElementById('mCallStatus');if(e)e.textContent=t}
function installButtons(){style();let b=document.getElementById('mmsCallBtn');if(!b){b=E('button','btn','☎ Bellen');b.id='mmsCallBtn';b.onclick=dial;document.querySelector('.actions')?.insertBefore(b,document.getElementById('guestBtn')||null)}let m=document.getElementById('mmsMobileCallBtn');if(!m){m=E('button','iconBtn','☎');m.id='mmsMobileCallBtn';m.setAttribute('aria-label','Bellen');m.onclick=dial;document.querySelector('.mobileTopActions')?.insertBefore(m,document.getElementById('mobileLockBtn')||null)}b.disabled=!token;m.disabled=!token}
function ready(){installButtons();if(!incomingTimer)incomingTimer=setInterval(checkIncoming,1800);checkIncoming()}

function dial(){if(!token||!selfId)return alert('Ontgrendel eerst MMS.');const l=layer();l.innerHTML='';const c=E('div','mCall');c.append(E('div','mCallAv','☎'),E('div','mCallName','MMS bellen'),E('div','mCallStatus','Voer een MMS-ID of gekoppeld telefoonnummer in.'));const f=E('div','mCallField'),lab=E('label','','MMS-ID of telefoonnummer'),i=E('input');i.placeholder='+31612345678 of MMS-ID';const er=E('div','mCallErr'),row=E('div','mCallRow'),x=E('button','btn','Annuleren'),go=E('button','btn primary','Bel');x.onclick=closeLayer;go.onclick=async()=>{go.disabled=true;er.textContent='';try{let peer=i.value.trim();if(peer.startsWith('+')){const r=await api(CORE,'/api/discover',{method:'POST',body:JSON.stringify({requesterId:selfId,phone:peer})});peer=r.profile?.id||''}if(!/^[A-Za-z0-9_-]{16,80}$/.test(peer))throw new Error('Geen geldig MMS-contact gevonden.');if(peer===selfId)throw new Error('Je kunt jezelf niet bellen.');await outgoing(peer)}catch(e){er.textContent=human(e);go.disabled=false}};i.onkeydown=e=>{if(e.key==='Enter')go.click()};f.append(lab,i);row.append(x,go);c.append(f,er,row,E('div','mCallTiny','Audio loopt via WebRTC en wordt niet door MMS/Supabase opgeslagen. De signaling-service verwerkt wel tijdelijke WebRTC-verbindingsmetadata.'));l.append(c);openLayer();setTimeout(()=>i.focus(),0)}

function makePC(stream){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}],iceCandidatePoolSize:2});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{let a=document.getElementById('mmsRemoteAudio');if(!a){a=document.createElement('audio');a.id='mmsRemoteAudio';a.autoplay=true;a.playsInline=true;document.body.append(a)}a.srcObject=e.streams[0];a.play().catch(()=>setStatus('Verbonden — tik op het scherm als je geen geluid hoort.'))};pc.onconnectionstatechange=()=>{if(!active||active.pc!==pc)return;const s=pc.connectionState;if(s==='connected')setStatus('Verbonden');else if(s==='connecting')setStatus('Verbinden…');else if(['failed','disconnected'].includes(s))setStatus('Verbinding onderbroken')};return pc}
function showCall(peer,status){const l=layer();l.innerHTML='';const c=E('div','mCall');const st=E('div','mCallStatus',status);st.id='mCallStatus';c.append(E('div','mCallAv','M'),E('div','mCallName',short(peer)),st);const a=E('div','mCallActions'),mw=E('div'),mute=E('button','mCallRound','🎙'),hw=E('div'),hang=E('button','mCallRound no','✕');mute.onclick=()=>toggleMute(mute);hang.onclick=()=>finish(true);mw.append(mute,E('div','mCallLabel','Mute'));hw.append(hang,E('div','mCallLabel','Ophangen'));a.append(mw,hw);c.append(a);l.append(c);openLayer()}
async function outgoing(peer){if(!supported())throw new Error('Bellen wordt door deze browser niet ondersteund.');if(active)throw new Error('Er is al een oproep actief.');let stream=null,pc=null;try{stream=await mic();pc=makePC(stream);const id=randId();active={id,peer,pc,stream,dir:'out',muted:false};showCall(peer,'Bellen…');const offer=await pc.createOffer({offerToReceiveAudio:true});await pc.setLocalDescription(offer);await waitIce(pc);await api(CALL,'/start',{method:'POST',body:JSON.stringify({callerId:selfId,calleeId:peer,callId:id,offer:pc.localDescription})});signal();keepAwake()}catch(e){if(active)await finish(false);else{stream?.getTracks().forEach(t=>t.stop());pc?.close()}throw e}}

async function checkIncoming(){if(!token||!selfId||active||document.hidden)return;try{const r=await api(CALL,'/incoming/'+encodeURIComponent(selfId));const c=r.calls?.[0];if(c&&c.id!==lastIncoming){lastIncoming=c.id;incoming(c)}}catch{}}
function incoming(c){const l=layer();l.innerHTML='';const card=E('div','mCall');card.append(E('div','mCallAv','☎'),E('div','mCallName',short(c.caller_id)),E('div','mCallStatus','Inkomende MMS-oproep'));const a=E('div','mCallActions'),nw=E('div'),no=E('button','mCallRound no','✕'),yw=E('div'),yes=E('button','mCallRound ok','☎');no.onclick=()=>decline(c);yes.onclick=()=>answer(c);nw.append(no,E('div','mCallLabel','Weiger'));yw.append(yes,E('div','mCallLabel','Neem op'));a.append(nw,yw);card.append(a);l.append(card);openLayer();navigator.vibrate?.([180,100,180])}
async function answer(c){let stream=null,pc=null;try{if(!supported())throw new Error('Bellen wordt door deze browser niet ondersteund.');const r=await api(CALL,'/signals/'+encodeURIComponent(c.id)+'?id='+encodeURIComponent(selfId));const offer=r.signals?.find(x=>x.kind==='offer')?.payload;if(!offer)throw new Error('De oproepdata is niet meer beschikbaar.');stream=await mic();pc=makePC(stream);active={id:c.id,peer:c.caller_id,pc,stream,dir:'in',muted:false};showCall(c.caller_id,'Verbinden…');await pc.setRemoteDescription(offer);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);await api(CALL,'/answer/'+encodeURIComponent(c.id),{method:'POST',body:JSON.stringify({calleeId:selfId,answer:pc.localDescription})});signal();keepAwake()}catch(e){if(active)await finish(false);else{stream?.getTracks().forEach(t=>t.stop());pc?.close()}alert(human(e));await decline(c,true)}}
async function decline(c,silent=false){try{await api(CALL,'/decline/'+encodeURIComponent(c.id),{method:'POST',body:JSON.stringify({calleeId:selfId})})}catch{}lastIncoming=c.id;closeLayer();if(!silent)navigator.vibrate?.(30)}

function signal(){stopSignal();signalTimer=setInterval(pollSignal,900);pollSignal()}
function stopSignal(){if(signalTimer){clearInterval(signalTimer);signalTimer=null}}
async function pollSignal(){if(!active)return;try{const r=await api(CALL,'/signals/'+encodeURIComponent(active.id)+'?id='+encodeURIComponent(selfId));for(const s of r.signals||[]){if(s.kind==='answer'&&active.dir==='out'&&s.payload){await active.pc.setRemoteDescription(s.payload);setStatus('Verbinden…')}else if(s.kind==='decline'){setStatus('Oproep geweigerd');setTimeout(()=>finish(false),700)}else if(s.kind==='hangup'){setStatus('Gesprek beëindigd');setTimeout(()=>finish(false),350)}}if(r.state==='missed'){setStatus('Geen antwoord');setTimeout(()=>finish(false),700)}else if(r.state==='declined'){setStatus('Oproep geweigerd');setTimeout(()=>finish(false),600)}}catch(e){console.warn('MMS call:',e.message)}}
function toggleMute(b){if(!active)return;active.muted=!active.muted;active.stream.getAudioTracks().forEach(t=>t.enabled=!active.muted);b.textContent=active.muted?'🔇':'🎙';setStatus(active.muted?'Microfoon gedempt':'Verbonden')}
async function finish(notify){const a=active;if(!a){closeLayer();return}active=null;stopSignal();stopAwake();try{a.stream?.getTracks().forEach(t=>t.stop());a.pc?.close()}catch{}const r=document.getElementById('mmsRemoteAudio');if(r){r.srcObject=null;r.remove()}closeLayer();if(notify&&token){try{await api(CALL,'/hangup/'+encodeURIComponent(a.id),{method:'POST',body:JSON.stringify({id:selfId})})}catch{}}}
function keepAwake(){stopAwake();keepTimer=setInterval(()=>{if(active)window.dispatchEvent(new Event('mousemove'))},25000)}
function stopAwake(){if(keepTimer){clearInterval(keepTimer);keepTimer=null}}

addEventListener('pagehide',()=>{if(active)finish(true);if(incomingTimer)clearInterval(incomingTimer);stopSignal();stopAwake()});
addEventListener('online',checkIncoming);
installButtons();
console.info('MMS Calls 0.12.1');
